### ISSUE TITLE
DubinsState space implementation not using set classification

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ompl/ompl#1014]
**Problem Description**
While the DubinsStateSpace implementation mentions the Dubins set classification method(A.M. Shkel and V. Lumelsky, “Classification of the Dubins set,” Robotics and Autonomous Systems, 34(4):179-202, 2001), the implementation computes the Dubins distance exhaustively.

https://github.com/ompl/ompl/blob/55588baaccbf4b48da926939e87f76d2f717ff70/src/ompl/base/spaces/DubinsStateSpace.h#L56-L62

@mamoll Was there a specific reason that the Dubins set classification scheme was not implemented? or is this a matter of a missing implementation? If it is the latter, I would be interested in contributing the implementation for the potential speedup of a factor of 2-3.

**Comment by mamoll** [comment]
No, there was no reason I didn't do it. Implementing this state space was a bit of side project without an immediate need, so I considered the current implementation "good enough" at the time. If you implement this, please do measure the speed up. I'm curious to see how much of a difference it makes.

**Comment by Jaeyoung-Lim** [comment]
@mamoll Thanks! These are some primary results on my side constrained to the long path case

![bitmap](https://user-images.githubusercontent.com/5248102/229501342-96b2f9d8-8c4a-471b-b6fa-7749b94d15bb.png)

**Comment by zkingston** [comment]
Wow, great speed up. I would definitely review a PR that implements these changes.

**Comment by Jaeyoung-Lim** [comment]
Closing as addressed in #1080
