### ISSUE TITLE
By test AIT* we got several log info such as  " Found a new exact solution of cost  ", but the  value of cost first decreases then suddenly increases and then decreases again

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1021]
AIT* is an optimizing planner, and we test it in  moveit  https://github.com/alaflaquiere/moveit-fork which integrate ompl 1.6.0
We focus on the path length rather than the speed, in moveit  we set  group planning time  5s,in a p2p in joint space plan demo 
![image](https://user-images.githubusercontent.com/13350158/233235159-4a50470d-8588-4d62-a800-1b69530f2291.png)

We got several log info such as  " Found a new exact solution of cost  ", but the  value of cost first decreases then suddenly increases and then decreases again,here is the log info  :
![image](https://user-images.githubusercontent.com/13350158/233233286-9b4868cb-ce4b-47ce-b3df-88c384bc510e.png)
![image](https://user-images.githubusercontent.com/13350158/233233340-8ed8e31c-b642-4cf4-9735-2142bb487815.png)
![image](https://user-images.githubusercontent.com/13350158/233233369-719a236b-fb89-456e-9d31-8100dff6a82c.png)

**we can see from the log that, the cost value is:11.5320->10.0759->10.0755->7.2064-> 16.1385(here suddenly increases,and then decrease)->13.7333->13.1666->12.8491->10.3396->9.2996.**
**Question:**
1)Why the  value of cost first decreases then suddenly increases and then decreases again in moveit when call AIT*
2)Which one is the  cost  we take finally,  is it 9.2996 or 7.2064

**Comment by zkingston** [comment]
The logs contain two separate planning queries, the first of which goes from around 11 -> 7 cost, the second goes from 16 -> 9. AIT* is planning without knowledge of the prior solution, and finds different solutions each time.

**Comment by dbdxnuliba** [comment]
@alaflaquiere,what your opinio
