### ISSUE TITLE
ompl_app.py outputs ModuleNotFoundError: No module named 'ompl.base._base'

### ISSUE THREAD

**Issue by IEI245MU5** [ompl/ompl#1025]
I have installed ompl using the installation script on a fresh ubuntu 20.04 system. When I try to launch the ompl.app GUI I get the following output:

```
$ /bin/python3 /home/kaiwen/Downloads/omplapp-1.6.0-Source/gui/ompl_app.py
Traceback (most recent call last):
  File "/home/kaiwen/Downloads/omplapp-1.6.0-Source/gui/ompl_app.py", line 58, in <module>
    from ompl import geometric as og
  File "/home/kaiwen/Downloads/omplapp-1.6.0-Source/ompl/py-bindings/ompl/geometric/__init__.py", line 1, in <module>
    from ompl import base
  File "/home/kaiwen/Downloads/omplapp-1.6.0-Source/ompl/py-bindings/ompl/base/__init__.py", line 2, in <module>
    from ompl.base._base import *
ModuleNotFoundError: No module named 'ompl.base._base'
```
Here is the CMakeCache.txt from the build/Release directory:
[CMakeCache.txt](https://github.com/ompl/ompl/files/11344499/CMakeCache.txt)

I would greatly appreciate any help.

**Comment by zkingston** [comment]
It appears that everything was found appropriate for your Python installation. Rather than using the downloaded source, could you clone the repo at the current `main` branch and try to rebuild? There were some previously noted issues with Python binding compilation.

**Comment by zkingston** [comment]
Did you clone the repo with submodules? Failure to find those cmake modules means you probably cloned the `omplapp` repo without the sub-`ompl` module, do a `git submodule update --init --recursive` in the `omplapp` directory and try again.

**Comment by IEI245MU5** [comment]
Hi, thank you that was the issue with building the repo.

I was now able to build the repo successfully, but I still face the same issue as before:
```
~/Downloads/omplapp/gui$ ./ompl_app.py 
Traceback (most recent call last):
  File "./ompl_app.py", line 58, in <module>
    from ompl import base as ob
  File "/home/kaiwen/Downloads/omplapp/ompl/py-bindings/ompl/base/__init__.py", line 2, in <module>
    from ompl.base._base import *
ModuleNotFoundError
[CMakeCache.txt](https://github.com/ompl/ompl/files/11430961/CMakeCache.txt)
: No module named 'ompl.base._base'

```
I have attached the [CMakeCache.txt](https://github.com/ompl/ompl/files/11430962/CMakeCache.txt)

**Comment by zkingston** [comment]
Did you run `make update_bindings` successfully?

**Comment by zkingston** [comment]
Can you check the output of the `build` directory to confirm if the `pypp.*` files were generated? This should be in, e.g., `build/py-bindings/bindings/util`. If there are the `pypp.{cpp,hpp}` files, then you might need to just run `make` again. If not, then the binding process failed.

**Comment by IEI245MU5** [comment]
The `build/Release/py-bindings/bindings` directory is empty except an `app.h` file

**Comment by zkingston** [comment]
Go into the `ompl` subdirectory and checkout the current main branch, this error has been fixed by more recent commits, specifically by #980
