### ISSUE TITLE
Ompl works on ros2 humble?

### ISSUE THREAD

**Issue by jsvsebastian** [ompl/ompl#1029]
hi, I'm designing an autonomous underwater vehicle, now in the stage of control and planning, but I´m stuck because I can't find any information about  if Ompl working in ros2 humble,

**Comment by zkingston** [comment]
Yes, OMPL is available in ROS 2. For example, see [MoveIt](https://github.com/ros-planning/moveit2) for an example of a ROS 2 library that uses OMPL for planning.
