### ISSUE TITLE
/usr/bin/ld: ../lib/libompl.so.1.6.0: undefined reference to `dBodyGetQuaternion(dxBody*)'

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1032]
```
dell@dell-NUC8i7BEH:~/refer/ompl/build/Release$ cmake ../.. -DPYTHON_EXEC=/usr/bin/python3.8
dell@dell-NUC8i7BEH:~/refer/ompl/build/Release$ make -j 4 update_bindings
dell@dell-NUC8i7BEH:~/refer/ompl/build/Release$ make -j 4
```
![image](https://user-images.githubusercontent.com/13350158/236715192-e7f6d5f7-311a-430e-9ad3-b0c17e74b881.png)

**Comment by zkingston** [comment]
It appears again that `ode` is missing somehow from your installation. For ubuntu, you should be able to install `ode` with `apt-get install libode-dev`. Confirm that `ode` is installed with `pkg-config --libs ode` which should give you something like `-lode`. If that appears correct, look at your `CMakeCache.txt` in the `build/` directory and find the section with the `ODE_*` variables: these should be filled in.

**Comment by dbdxnuliba** [comment]
@zkingston  yes ,dell@dell-NUC8i7BEH:~/refer$ pkg-config --libs ode
-lode

and in CMakeCache.txt in the build/Release directory 
![image](https://user-images.githubusercontent.com/13350158/236968727-8287ee88-6b67-4493-8567-afb0c0d724ab.png)
![image](https://user-images.githubusercontent.com/13350158/236968761-369e7572-87d5-4186-9098-945b3776ad22.png)
 is 
so what should I fill in the ODE_*

**Comment by zkingston** [comment]
Closing your current issues, please open another one if you still have troubles with installation.

**Comment by dbdxnuliba** [comment]
ok
