### ISSUE TITLE
[update_bindings](make: *** No rules to make target 'update_bindings'. stop.)

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1035]
ubuntu18.04 melodic python3:python3.8
[update_bindings](make: *** No rules to make target 'update_bindings'. stop.)
~/ref/ompl$ bash install-ompl-ubuntu.sh.in --python

![image](https://github.com/ompl/ompl/assets/13350158/6adc3184-da72-4812-ad13-8794bf7b7b6c)
![image](https://github.com/ompl/ompl/assets/13350158/2f8a2412-4e6d-4a30-aaae-89292a781254)

[update_bindings](make: *** No rules to make target 'update_bindings'. stop.)

**Comment by zkingston** [comment]
It appears that `numpy` is missing from your system, please install and try again. Complete remove the build directory and create another.

**Comment by dbdxnuliba** [comment]
after sudo apt-get install python3.8-dev ,it can continue compile,thanks

**Comment by Shihao-Feng-98** [comment]
I have the same error in ubuntu20, and I also have a question about how to install pybindings in conda?
