### ISSUE TITLE
from ompl import base as ob     ^ IndentationError: unexpected indent

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1037]
after install ompl with script: bash install-ompl-ubuntu.sh.in --python
![image](https://github.com/ompl/ompl/assets/13350158/5118b9b7-9397-4b9d-a7bb-b3966abd04c5)
![image](https://github.com/ompl/ompl/assets/13350158/b4ceae24-df5a-4dd3-a7bf-019ed15c93e9)

![image](https://github.com/ompl/ompl/assets/13350158/863d4669-13af-40eb-ac65-e8ed9824724c)

**when I use ompl in python3**

 **from ompl import base as ob
  File "<stdin>", line 1
    from ompl import base as ob
    ^
IndentationError: unexpected indent**
dell@dell-NUC11PAHi7:~/$ python3
Python 3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ompl
>>>  from ompl import base as ob
  File "<stdin>", line 1
    from ompl import base as ob
    ^
IndentationError: unexpected indent
>>> 

**and when i install ompl with script 
some info shows like：**

File "/usr/local/lib/python3.8/dist-packages/pyplusplus/utils/init.py", line 129, in load
f = open( fpath, 'r+b' )
**FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base'**

Here is the details：

bash install-ompl-ubuntu.sh.in --python
image

-- The following Python modules were found:

numpy pyplusplus pygccxml
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/build/Release
[100%] Built target update_control_bindings
[100%] Creating C++ code for Python module tools (see pyplusplus_tools.log)
Replacing member function ::ompl::base::OptimizationObjective::print
Replacing member function ::ompl::base::GoalRegion::print
Replacing member function ::ompl::base::Goal::print
Replacing member function ::ompl::base::ProblemDefinition::print
Replacing member function
::ompl::base::ScopedStateompl::base::StateSpace::print
Replacing member function ::ompl::base::Path::print
Replacing member function ::ompl::base::ProjectionMatrix::print
Replacing member function ::ompl::base::ParamSet::print
Replacing member function ::ompl::tools::SelfConfig::print
Replacing member function ::ompl::geometric::PathGeometric::print
Replacing member function ::ompl::geometric::SimpleSetup::print
Replacing member function ::ompl::control::SimpleSetup::print
Replacing member function ::ompl::control::PathControl::print
Replacing member function
::ompl::tools::Benchmark::saveResultsToStream
Replacing member function
::ompl::tools::Benchmark::setPlannerSwitchEvent
Replacing member function ::ompl::tools::Benchmark::setPreRunEvent
Replacing member function ::ompl::tools::Benchmark::setPostRunEvent
Traceback (most recent call last):
File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/generate_bindings.py", line 983, in
globals()['ompl_'+module+'_generator_t'](https://github.com/ompl/ompl/issues/1036)
File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/generate_bindings.py", line 880, in init
code_generator_t.init(self, 'tools',
File "/home/dell/ref/ompl/ompl-db4e6bf581cd531462ce8a3fa1889a659bd1c4b0/py-bindings/ompl/bindings_generator.py", line 154, in init
self.mb.register_module_dependency(dep)
File "/usr/local/lib/python3.8/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 142, in register_module_dependency
db.load( other_module_generated_code_dir )
File "/usr/local/lib/python3.8/dist-packages/pyplusplus/utils/init.py", line 129, in load
f = open( fpath, 'r+b' )
FileNotFoundError: [Errno 2] No such file or directory: 'bindings/base'
-- Build type: Release
-- Checking for module 'libspot'
-- No package 'libspot' found
-- Could NOT find spot (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS)
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"
-- The following features have been enabled:

OMPL_VERSIONED_INSTALL, Whether to install header files in
/include/ompl-X.Y/ompl, where X and Y are the major and minor
version numbers
OMPL_BUILD_PYBINDINGS, Whether to build the Python bindings.
OMPL_BUILD_PYTESTS, Whether to build/run the python binding unit tests.
OMPL_BUILD_TESTS, Whether to build the unit tests.
OMPL_BUILD_DEMOS, Whether to build the OMPL demo programs.
-- The following OPTIONAL packages have been found:

**So could you please tell me how to fix the problem**

**Comment by zkingston** [comment]
Closing in favor of #1036, please don't open multiple issues for the same problem.
