### ISSUE TITLE
  file INSTALL destination: /usr/local/share/man/man1 is not a directory.

### ISSUE THREAD

**Issue by dbdxnuliba** [ompl/ompl#1038]
bash install-ompl-ubuntu.sh --python

-- Up-to-date: /usr/local/share/ompl/demos/VFRRT/VectorFieldNonconservative.cpp
-- Up-to-date: /usr/local/share/ompl/demos/VFRRT/plotConservative.py
-- Up-to-date: /usr/local/share/ompl/demos/VFRRT/plotNonconservative.py
-- Up-to-date: /usr/local/share/ompl/demos/VFRRT/VectorFieldConservative.cpp
-- Installing: /usr/local/bin/ompl_benchmark_statistics.py
CMake Error at doc/cmake_install.cmake:46 (file):
  file INSTALL destination: /usr/local/share/man/man1 is not a directory.
Call Stack (most recent call first):
  cmake_install.cmake:71 (include)

**Comment by zkingston** [comment]
Closing your current issues, please open another one if you still have troubles with installation.
