### ISSUE TITLE
Reactive Motion Planning for 7 DoF Robot Arm using OMPL

### ISSUE THREAD

**Issue by im-renpei** [ompl/ompl#1045]
Hi everyone,

I would like to seek some advice on implementing reactive motion planning for my 7 Degree of Freedom (DoF) robot arm using OMPL. Currently, I am able to use OMPL's RRT-Connect planner for motion planning within the joint space of my robot arm, which is a 7-dimensional space. However, I am facing a challenge when it comes to dynamic scenarios, such as moving targets or obstacles in the environment. I'm wondering if it is possible to achieve reactive motion planning with OMPL in these cases.

Thank you in advance for any insights you can provide.

**Comment by zkingston** [comment]
Unfortunately, there is no easy solution to dynamic and moving obstacles.

The simplest way to achieve reactive motion planning is with replanning, where you simply call the planner again (after clearing internal structures). You can also try to use the experience-based planners, [Lightning](https://ompl.kavrakilab.org/classompl_1_1tools_1_1Lightning.html) and [Thunder](https://ompl.kavrakilab.org/classompl_1_1tools_1_1Thunder.html), which gather experience over many queries and typically perform faster over time.
