### ISSUE TITLE
Breakpoints not working when running  demos

### ISSUE THREAD

**Issue by liangxu1109** [ompl/ompl#1052]
When running a demo(SE3RigidBodyPlanning), and when I tried to debug by setting breakpoints, it didn't work. The program just finished running. Can you help me?

**Comment by zkingston** [comment]
You probably have set a breakpoint outside the control flow of the program. I would double check that the location of the breakpoint would actually be called by your program. Unfortunately, I do not have time to give debugging help outside of OMPL errors.
