### ISSUE TITLE
Add KBoundedStrategy ConnectionStrategy to Python bindings?

### ISSUE THREAD

**Issue by sageshoyu** [ompl/ompl#1054]
I've tried to use a connection-radius-like `ConnectionStrategy` on your PRM planner, but the bindings only seem to offer `KStrategy` and `KStarStrategy`. Would it be possible to add KBoundedStrategy to the bindings?

**Comment by zkingston** [comment]
Sure, take a look at https://github.com/ompl/ompl/pull/1055

**Comment by sageshoyu** [comment]
Thank you!
