### ISSUE TITLE
Trouble installing OMPL on M1 Macbook

### ISSUE THREAD

**Issue by awesome-aj0123** [ompl/ompl#1063]
Can someone please provide a detailed list of instructions to installing OMPL on a M1 Macbook. I am currently trying to use the installation steps [here](https://ompl.kavrakilab.org/core/installation.html) (under macOS homebrew), but am running into the following issue on the second step.

```
pypy3: The x86_64 architecture is required for this software.
Error: pypy3: An unsatisfied requirement failed this build.
```

I require OMPL with Python bindings as I will mostly be coding in Python and am not as comfortable with installing libraries. Any help on this is much appreciated!

**Comment by zkingston** [comment]
You can generate the Python bindings without `pypy`. Simply do not install `pypy` and run through the installation steps like normal. Note that the binding generation will probably take quite some time.

**Comment by awesome-aj0123** [comment]
When I try to run the command `make -j 4 update_bindings`,  I run into this:
`make: *** No rule to make target 'update_bindings'.  Stop.`

What can I do from here to install the python bindings?

**Comment by fmg-lydonchandra** [comment]
try `cmake ../.. -D OMPL_BUILD_PYBINDINGS:BOOL=ON

**Comment by zkingston** [comment]
Please see #1098

**Comment by bakuljangley** [comment]
@awesome-aj0123 did you get it to work? I'm trying on an apple m2 and I get the same error when I try to update the python bindings
