### ISSUE TITLE
Tutorials about python bindings 

### ISSUE THREAD

**Issue by zichunxx** [ompl/ompl#1071]
Hi!

I just built Python bindings and want to construct a plan task with a redundant manipulator.

However, I didn't find any demos or tutorials about using Python bindings to perform a high-DOF task with some obstacles or maybe I missed something.

Hence, my question is how to add some obstacles with different shapes effectively and finish a motion planning task. 

Are there some demos available? 

Any help would be appreciated!

Thanks!

**Comment by ChamzasKonstantinos** [comment]
This is the way OMPl.app uses it: [link](https://github.com/ompl/omplapp/blob/main/src/omplapp/geometry/detail/FCLMethodWrapper.h)
You can also check other software that use OMPL under the hood [here](https://ompl.kavrakilab.org/integration.html)  maybe one of them would suit your purposes better.
