### ISSUE TITLE
How to specify continuous collision checking in OMPL.app

### ISSUE THREAD

**Issue by IEI245MU5** [ompl/ompl#1077]
Hello,

OMPL.app uses FCL's discrete collision checking by default. How do I specify that FCL's continuous collision checking or any other collision checking method should be used?

I am a bit confused as setup.[setStateValidityCheckerType](https://ompl.kavrakilab.org/classompl_1_1app_1_1RigidBodyGeometry.html#a1193a5ac3418afca23a00620178ce1da) only differentiates between PQP and FCL.

I am also unsure how to use the [setStateValidityChecker](https://ompl.kavrakilab.org/classompl_1_1geometric_1_1SimpleSetup.html#a6774bcc65c0968e2cb927bab464a3aad) and [allocStateValidityChecker](https://ompl.kavrakilab.org/classompl_1_1app_1_1RigidBodyGeometry.html#a0c2e87c6f133d7cd2918d9856b215d22) function. 

An explanation is greatly appraciated. Thank you

**Comment by mamoll** [comment]
See also [this demo](https://github.com/ompl/omplapp/blob/main/demos/SE3RigidBodyPlanning/CollisionCheckers.cpp) that shows how to use PQP, FCL discrete, and FCL continuous for the same problems.

**Comment by IEI245MU5** [comment]
Is setting the State Validity Checking Resolution relevant for continuous collision checking? To my understanding of continuous cc there is no resolution to be set, but the demo calls `setup.getSpaceInformation()->setStateValidityCheckingResolution(0.01); `regardless of what cc method is used.

My own testing leads me to believe that the continuous cc is not influenced by the resolution.
