### ISSUE TITLE
Stride length of member variables != 1, cannot translate into dense vector

### ISSUE THREAD

**Issue by joao-pm-santos96** [ompl/ompl#1086]
Hello developers.
Thank you for such as amazing library. It is truly wondaful!

In python, I am trying to build a constrained plan in which I want to prioritize some joints motion more than other. To do so, I am creating an CompoundStateSpace() using the addSubspace() method. Yet, when I try to plan, I get the following erro:

```bash
solved = ss.solve(max_time)
RuntimeError: ompl::base::ConstrainedStateSpace::setup(): Stride length of member variables != 1, cannot translate into dense vector.
```
 
Am I doing something wrong? Is this even possible?

**Comment by zkingston** [comment]
Unfortunately the constrained state spaces are limited to contiguous memory, which means compound state spaces will not work (see some of the limitations in https://ompl.kavrakilab.org/constrainedPlanning.html).

I would subclass the RealVectorStateSpace class and change the distance function to add the appropriate weighting/interpolation/etc. functions.
