### ISSUE TITLE
RRTstar obtain obstacles information

### ISSUE THREAD

**Issue by Panda12580** [ompl/ompl#1095]
Hello, Mark. I'm a beginner in motion planning, and I want to implement robot motion planning using the RRTStar algorithm from your team's ompl library. However, I'm facing a challenge in motion planning: I'm not sure how to obtain information about obstacles in the state space (typically, their positions in the state space) to impose sampling constraints. I've looked closely at the spaceinformation class but I'm unsure how to access obstacle information. I sincerely hope you can help me solve this problem, and I'm looking forward to your response.

**Comment by zkingston** [comment]
The obstacle information is provided by you in the state validity checker. You could implement a custom class (see the [tutorial](https://ompl.kavrakilab.org/stateValidation.html)) that provides validity checking, and give access to the relevant data structures you need in that class for other parts of your code. The state validity checker can be accessed through the space information with [getStateValidityChecker](https://ompl.kavrakilab.org/classompl_1_1base_1_1SpaceInformation.html#ac6d23843c9489c59e8faad6e1d4faf29).
