### ISSUE TITLE
ModuleNotFoundError: No module named 'ompl'

### ISSUE THREAD

**Issue by furkansariyildiz** [ompl/ompl#1108]
Hello everyone, I am trying to use demo example [PlannerData.py Example](https://ompl.kavrakilab.org/PlannerData_8py_source.html) via using python but it returns **ModuleNotFoundError: No module named 'ompl'** 

I am working on Ubuntu 20.04 and ROS2 Galactic.

**Comment by zkingston** [comment]
Consolidating this under #1110 - other Python binding error. Please move discussion there.
