### ISSUE TITLE
No rule to make target 'update_bindings'.

### ISSUE THREAD

**Issue by panthuncia** [ompl/ompl#1115]
I've installed the relevant dependencies, and I can build OMPL as a whole, but when I try to run "make -j 4 update_bindings" to build python bindings, I get "make: *** No rule to make target 'update_bindings'.  Stop."

If I build with the ubuntu install script with --python, I get:

 MORSE, <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Triangle, <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * flann (required version >= 1.8.3), <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * spot, <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.
 * Python, <https://www.python.org>
   Used for python bindings.

-- The following Python modules were found:

 * pyplusplus pygccxml

I'm not sure how python modules can be found, but python cannot. 

Platform: Ubuntu 20.04, Jetson nano, Python 3.11

**Comment by ccm010101** [comment]
@panthuncia 

How did you solve this problem?

Unlike you, I use mac M1 and experienced

```
(ompl) Doonams-MacBook-Pro:ompl chanmichoi$ make -j 8 update_bindings
make: *** No rule to make target `update_bindings'.  Stop.
```

I installed all dependencies (Boost, CMake, Eigen).
