### ISSUE TITLE
Path and speed optimization using OMPL

### ISSUE THREAD

**Issue by akash-venkateshwaran** [ompl/ompl#1127]
Hello,

I am working on a ship voyage optimization problem where I need to optimize the path based on fuel objectives as well as the speed along that path. This problem also has speed and time constraints. I am very new to OMPL. As far as I know, I couldn't find anything that optimizes the speed and path simultaneously. I am not sure how I would set up the space and constraints for this problem using OMPL. 

Looking forward to your suggestions. Thank you!

**Comment by mamoll** [comment]
Hi @akash-venkateshwaran, you may find [this tutorial](https://ompl.kavrakilab.org/optimizationObjectivesTutorial.html) that explains how you can define your own optimization objectives helpful. 

Re. speed/time constraints, there are different ways to handle this. A common way is to find a feasible path first and then parametrize this path with respect to time to get a trajectory. This second step can incorporate velocity & acceleration constraints (and sometimes even jerk constraints). (TOTG, TOPP, and Ruckig are some methods you could use for this step, which is not part of OMPL.) You can also formulate this as a kinodynamic planning problem and solve it using planners in the ompl::control namespace, but it is non-trivial to make this work well.
