### ISSUE TITLE
New Planner in Python

### ISSUE THREAD

**Issue by sadiq26** [ompl/ompl#1135]
I am using OMPL in order to create a new planner using OMPL. The documentation gives only a short description of how to do so:

[1]   Publicly derive the new class from ompl::base::Planner
[2]   Provide an implementation of the method solve() from ompl::base::Planner

I was wondering if these instructions can be extended to python as so far i have not been able to find anything on that.

**Comment by joao-pm-santos96** [comment]
like this? https://github.com/ompl/ompl/blob/5c3f6fb195fcdaeaa7247d7f228dc3fdf1c013c5/demos/RandomWalkPlanner.py#L53-L102

**Comment by zkingston** [comment]
This is correct!
