### ISSUE TITLE
G-RRT*

### ISSUE THREAD

**Issue by Pha1ton** [ompl/ompl#1186]
A paper named "Greedy Heuristics for Sampling-based Motion Planning in High-Dimensional State Spaces" propoesd an algorithm named G-RRT*. This paper says "Information on the OMPL implementations of G-RRT*
will be publicly made available at https://github.com/mlsdpk/ompl." and the repository mentioned is forked from ompl. I wonder if this G-RRT* algorithm is integrated into ompl. If so, where can I find the source code?

**Comment by zkingston** [comment]
It seems that paper is implemented on a branch of the fork you linked: https://github.com/mlsdpk/ompl/tree/greedyrrtstar

You'll have to build that forked OMPL to run their code.
