### ISSUE TITLE
Non-holonomic RRTstar

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#172]
**[Original report](https://bitbucket.org/ompl/ompl/issue/51) by Luis G. Torres (Bitbucket: [Luis Torres](https://bitbucket.org/Luis Torres), ).**

----------------------------------------

The current RRTstar implementation can handle geometric, non-holonomic configuration spaces like Dubins car. By "handle" I mean it can return trajectories without crashing. However, the modifications made to handle the non-holonomic cases don't really have any theoretical basis as far as asymptotic optimality.

[Recent work](http://ares.lids.mit.edu/papers/Karaman.Frazzoli.ICRA13.pdf) by Karaman and Frazzoli has resulted in a variant of RRTstar that does provide asymptotic optimality guarantees for some non-holonomic robots. It might be worth checking if we can incorporate this variant into our implementation of RRTstar, or if it would have to be its own separate planner.

**Comment by zkingston** [comment]
Closing due to age.
