### ISSUE TITLE
Triangle inequality

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#209]
**[Original report](https://bitbucket.org/ompl/ompl/issue/88) by Anonymous.**

----------------------------------------

Sanity checks for triangle inequality are buggy: line 672 of StateSpace.cpp reads :

            if ((flags & STATESPACE_TRIANGLE_INEQUALITY) && fabs(diff) > eps) ...

shouldn't it be    
 
 if ((flags & STATESPACE_TRIANGLE_INEQUALITY) && diff < eps)

**Comment by zkingston** [comment]
Fixed by #115
