### ISSUE TITLE
Need More Sample Code About The LTLPlanner and Creating Automaton

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#286]
**[Original report](https://bitbucket.org/ompl/ompl/issue/165) by wwei17 (Bitbucket: [wwei17](https://bitbucket.org/wwei17), GitHub: [wwei17](https://github.com/wwei17)).**

----------------------------------------

Hi,

I went over the LTLWithTriangluation.cpp file but did not fully understand the process of transferring a LTL formula into an automaton then into an automaton object.

```
#!c++

 //LTL co-safety sequencing formula: visit p2,p0 in that order
    std::vector<unsigned int> sequence(2);
    sequence[0] = 2;
    sequence[1] = 0;
    oc::AutomatonPtr cosafety = oc::Automaton::SequenceAutomaton(3, sequence);

    //LTL safety avoidance formula: never visit p1
    std::vector<unsigned int> toAvoid(1);
    toAvoid[0] = 1;
    oc::AutomatonPtr safety = oc::Automaton::AvoidanceAutomaton(3, toAvoid);
```
Above code is from ltlwithtriangluation.cpp. It is creating a automaton of ' F(2&F(0))&(!1)' if I understand it correctly. But can you provide more example of how to creating automaton providing LTL formula or providing automaton format. 

I have done some research and know that SPOT is one option to turn LTL formula into automaton format. for example:
![QQ截图20150831144327.png](https://bitbucket.org/repo/9pAaox/images/934190577-QQ%E6%88%AA%E5%9B%BE20150831144327.png)
```
#!automaon
HOA: v1
States: 4
Start: 0
AP: 3 "c" "a" "b"
acc-name: Buchi
Acceptance: 1 Inf(0)
properties: trans-labels explicit-labels state-acc
--BODY--
State: 0
[!0&!1 | !0&!2] 1
[!0&1&!2] 2
[!0&1&2] 3
State: 1
[!1 | !2] 1
[1&!2] 2
[1&2] 3
State: 2
[!2] 2
[2] 3
State: 3 {0}
[t] 3
--END--
```
Above code is for the automaton of LTL formula ' F(2&F(0))&(!1)' generated from SPOT.
but I don't understand how this automaton links to the one from ltlwithtriangluation.cpp.

Please give me some detail of the code and more samples of how to creating automaton object.

Wei

**Comment by DangMinh24** [comment]
Hi @mamoll, in your attached script [(https://www.cs.rice.edu/~mmoll/icaps2016/ltl2a.h.html)](https://www.cs.rice.edu/~mmoll/icaps2016/ltl2a.h.html), it seems like you have to traverse the BDD to check the true/false value of the logical expression. 

Is there any function to check the true/false value of the expression directly from BDD?

**Comment by mamoll** [comment]
@DangMinh24 you'd need to check the documentation for SPOT, the library used for the LTL formula-to-automaton conversion.

Note that the snippet of code you mentioned has since been properly integrated with OMPL:
https://github.com/ompl/ompl/blob/master/src/ompl/control/planners/ltl/src/Automaton.cpp#L84-L160
There is a demo to shows how to use this:
https://github.com/ompl/ompl/blob/master/demos/LTLWithTriangulation.cpp#L203

**Comment by DangMinh24** [comment]
Thank you @mamoll
