### ISSUE TITLE
Should freeState on const State pointers be allowed?

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#363]
**[Original report](https://bitbucket.org/ompl/ompl/issue/242) by scott paulin (Bitbucket: [Scott_P](https://bitbucket.org/Scott_P), ).**

----------------------------------------

In OMPL a base::State on the heap should be deleted with base::StateSpace::freeState. However, this freeState method is only defined for non-const State pointers. C++ allows const pointers to be deleted, should OMPL allow the use of freeState on const State pointers? This would allow more use of const State pointers throughout the library.

**Comment by zkingston** [comment]
Agree with preventing novice users from deleting const State *, closing unless further interest.
