### ISSUE TITLE
Mark all dll exports with cmakes GenerateExportHeader

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#507]
**[Original report](https://bitbucket.org/ompl/ompl/issue/386) by Anonymous.**

----------------------------------------

Any chance to convince you to mark your public classes by using cmakes GenerateExportHeader
https://cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html

I know its ugly, but its required to build on windows dll without hitting the symbol export limit per dll. And of course it makes the dll api cleaner in general on all platforms. And maybe the dll size smaller and link faster(?)

**Comment by zkingston** [comment]
Closing due to age.
