### ISSUE TITLE
Propagating

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#532]
**[Original report](https://bitbucket.org/ompl/ompl/issue/411) by Anonymous.**

----------------------------------------

Hi,

I would like to implement propagation in optimality planners such as RRT* and SST. In the planners,  it seems that a linear steering function is implemented, right? Do I need to change the planner code in order to use the StatePropagator (and ODESolver) to use propagation and not steering? Also, the tutorial for that explains how to setup the StatePropagator but not how to use it in practice in the planner code. Is there somewhere an example?

Thanks,
James.

**Comment by Georacer** [comment]
Is there a reason why custom steering functionality is not implemented for SST?
It would be nice to have it.

**Comment by mamoll** [comment]
I suspect that the reason this was done for theoretical reasons: to prove completeness or asymptotic near optimality it may have been necessary to sample over the entire control input space.
