### ISSUE TITLE
Multi-Query behavior (PRM planner)

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#575]
**[Original report](https://bitbucket.org/ompl/ompl/issue/454) by Jul Mz (Bitbucket: [julmz](https://bitbucket.org/julmz), GitHub: [julmz](https://github.com/julmz)).**

----------------------------------------

Hello

I am currently using a LazyPRMstar planner in a multi-query problem (same start, different successive goals) while keeping the same tree using a clearQuery() call between goals.
This works fine, however I noticed two minor things.

1/ There is the need to call ProblemDefinition->clearSolutionPaths() before setting a new goal, otherwise the planner sometimes uses the previous goal value (but not always).

2/ There is something strange with the display of the number of created states with a new call (thus, after the clearQuery call): most of the time it displays a small number of new nodes (as expected), but sometimes I get "Info:    LazyPRMstar: Created 4294967282 states" (this same exact number each time, while the number of states in structure did not increase that much).

Please find a sample c++ code below.

All the best

```
#!c++

    //StateSpace
    ob::StateSpacePtr space(new ob::RealVectorStateSpace(2));
    ob::RealVectorBounds bounds(2);
    bounds.low[0] = x_min_;
    bounds.high[0] = x_max_;
    bounds.low[1] = y_min_;
    bounds.high[1] = y_max_;
    space->as<ob::RealVectorStateSpace>()->setBounds(bounds);
    //SpaceInformation
    ob::SpaceInformationPtr info(new ob::SpaceInformation(space));
    info->setStateValidityChecker(std::bind(&planner::isStateValid, this, std::placeholders::_1));
    info->setup();
    //Problem definition
    ob::ProblemDefinitionPtr problem(new ob::ProblemDefinition(info));
    ob::ScopedState<> start(space);
    ob::ScopedState<> goal(space);
    //Planner
    og::LazyPRMstar prm_planner(info);
    prm_planner.setProblemDefinition(problem);
    //start init    
    start->as<ob::RealVectorStateSpace::StateType>()->values[0] = start_.position.x;
    start->as<ob::RealVectorStateSpace::StateType>()->values[1] = start_.position.y;

    //multi-query (loop on goals)
    uint nb_goals = goals_.size();
    for(uint j = 0; j < nb_goals; j++)
    {
        prm_planner.clearQuery();    
        goal->as<ob::RealVectorStateSpace::StateType>()->values[0] = goals_[j].position.x;
        goal->as<ob::RealVectorStateSpace::StateType>()->values[1] = goals_[j].position.y;
        problem->clearGoal();
        problem->clearSolutionPaths();
        problem->setStartAndGoalStates(start, goal);
        double planning_time = 1.0;
        ob::PlannerStatus solved = prm_planner.ob::Planner::solve(planning_time);
                
        if (solved)
        {
            //get path
            og::PathGeometric Path( dynamic_cast< const og::PathGeometric& >( *problem->getSolutionPath()));
            Path.print(std::cout);
        }
      }
```

**Comment by zkingston** [comment]
1. Solution paths need to be cleared as well.
2. The print statement in LazyPRM is suffering from subtracting milestones from the roadmap, I believe, removed due to these milestones being invalid - and the negative number (-13) is being printed as an unsigned value.
