### ISSUE TITLE
creating custom goal for FMT

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#615]
**[Original report](https://bitbucket.org/ompl/ompl/issue/494) by Sivaraman (Bitbucket: [sivaramanparamasivam](https://bitbucket.org/sivaramanparamasivam), ).**

----------------------------------------

I want to define  a custom goal for FMT. From what I understand reading previous issues,the goal state must be derived from the goalSampleableRegion. However even after deriving the goal state from goalSampleableRegion ,the program still returns "FMT: unknown type of goal" .How to create a goal state that is derived from the goalSampleableRegion in python?

**Comment by zkingston** [comment]
Closing due to same issue as #895
