### ISSUE TITLE
from ompl.util._util import * error

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#627]
**[Original report](https://bitbucket.org/ompl/ompl/issue/506) by Anonymous.**

----------------------------------------

I try to run ./ompl_app.py to start the gui, but got error

Traceback (most recent call last):
  File "./ompl_app.py", line 56, in <module>
    from ompl.util import OutputHandler, useOutputHandler, LogLevel, \
  File "/home/shuo/Downloads/omplapp-1.4.2-Source/ompl/py-bindings/ompl/util/__init__.py", line 4, in <module>
    from ompl.util._util import *
ImportError: dynamic module does not define init function (init_util)

**Comment by hlhfhmt** [comment]
i have the same problem, and  there is still no method to solve it.
