### ISSUE TITLE
Not able to import modules from ompl

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#628]
**[Original report](https://bitbucket.org/ompl/ompl/issue/507) by Sirineni Yahnit (Bitbucket: [Yahnit Sirineni](https://bitbucket.org/Yahnit Sirineni), ).**

----------------------------------------

Hey, so I'am trying to use the RRT* Algorithm for path planning and i have installed the python bindings of OMPL. When I'am trying to import modules such as 'base' and 'geometric' from ompl package, an error is being thrown that it is unable to import those packages. Below i have attached the error, please look into this.

#    from ompl import util as ou
    from ompl import base as ob
    from ompl import geometric as og

File "ompl_demo.py", line 9, in <module>
    from ompl import base as ob
ImportError: cannot import name 'base' from 'ompl' (/Users/yahnit/Documents/research/PATH PLANNING FOR FORMATIONS/simulation/Python-RVO2/ompl.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ompl_demo.py", line 18, in <module>
    from ompl import base as ob
ImportError: cannot import name 'base' from 'ompl' (/Users/yahnit/Documents/research/PATH PLANNING FOR FORMATIONS/simulation/Python-RVO2/ompl.py)

**Comment by iLUVE69** [comment]
facing similar issues, im trying to run python demos and it throws an error saying ompl.util.__util__ not found. I believe ive installed OMPL correctly but that was a huge pain in itself and im not sure if the files are all good
