### ISSUE TITLE
Adding new Planners to ompl_app

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#669]
**[Original report](https://bitbucket.org/ompl/ompl/issue/548) by bf (Bitbucket: [bf](https://bitbucket.org/bf), GitHub: [bf](https://github.com/bf)).**

----------------------------------------

Hi,

I was trying to add new planners to the ompl\_app, but encountered some issues during the creation of the python bindings.

I followed the steps here: [http://ompl.kavrakilab.org/pybindingsPlanner.html](http://ompl.kavrakilab.org/pybindingsPlanner.html)

Which means: I added the planners to omplapp/ompl/src/ompl/geometric/planners and edited the headers\_geometric.txt at omplapp/ompl/py-bindings, then generated the new bindings via “make clean\_bindings” and “make update\_bindings”\(in omplapp/build/Release\). After building the app with “make” and “sudo make install” \(in omplapp/build/Release\), the app works, but the new planners don’t show up.

I tried looking into the pyplusplus\_geometric.log at omplapp/build/Release, but there I could not find anything regarding the new planners and they don’t show up in the build-folder anywhere.

What do I have to do to create fitting python-bindings?  
I attached the planner-headers, headers\_geometric and the pypluplus\_geometric.log.

I use Ubuntu 16.4.6 and have libspot installed.

**Comment by zkingston** [comment]
It would be possible, similar to the [special case for Syclop](https://github.com/ompl/omplapp/blob/main/gui/ompl_app.py#L494) to have OMPL.app provide some default quotient spaces for the SE2/SE3 spaces used in the program. This kind of pull request would be welcome, but we do not plan to do that ourselves at this time.
