### ISSUE TITLE
OMPL CUDA Support

### ISSUE THREAD

**Issue by mamoll** [ompl/ompl#677]
**[Original report](https://bitbucket.org/ompl/ompl/issue/556) by Connor Lawson (Bitbucket: [rclawson](https://bitbucket.org/rclawson), GitHub: [rclawson](https://github.com/rclawson)).**

----------------------------------------

I propose enabling CUDA compilation in the OMPL build system. This addition would allow GPU-enabled planners to exist in the main OMPL codebase, where currently they can only be added as external libraries if at all.

As of CMake 3.12, CUDA is supported as an additional language and is fairly easy to compile alongside regular C\+\+ code. Based on some initial experiments, merely enabling CUDA language and adding CUDA files does not work due to incompatible compiler flag settings.

For a build system, the main tasks would be

* Bump required CMake version to 3.12
* Enable CUDA language at top level and associate file extensions \(\*.cu, typically\)
* Add options for conditional compilation of CUDA-dependent code
* Detect presence and version of CUDA on the system
* Rework compiler flag settings to accommodate the CUDA compiler

Initially, CUDA-enabled planners could be added as separate compilation units and merely disabled when CUDA is not present on the compiling system. Over time, CUDA functionality can be back-ported to existing planners by incorporating components such as samplers and collision detectors that support GPU execution.

Parallelization in planning is gaining traction and promising large speedups in certain use cases. Aside from whole planners like GMT\*, papers have also come out describing parallel sampling and collision detection, among other techniques. OMPL already includes several algorithms that are parallelized on the CPU, but a growing class of recent techniques specifically target the GPU. These cannot be expressed in the current library. Adding build support for CUDA would benefit the community by allowing all the tools currently built around OMPL to benefit from these advances and by maintaining a centralized repository for high-quality motion planning implementations.

**Comment by jih189** [comment]
any update about using CUDA in ompl?
