### ISSUE TITLE
How does the MechanicalWorkOptimization.cpp work?

### ISSUE THREAD

**Issue by tsoratan** [ompl/ompl#680]
Hi,

I am looking into the code to figure out the method you use to calculate mechanical work in MechanicalWorkOptimization.cpp [https://github.com/ompl/ompl/blob/master/src/ompl/base/objectives/src/MechanicalWorkOptimizationObjective.cpp](url)

I am not sure, but from my understanding, `ompl::base::MechanicalWorkOptimizationObjective::stateCost` will always return 1.0, and in `ompl::base::MechanicalWorkOptimizationObjective::motionCost`, the `positiveCostAccrued` would always return 0. It seems to me that `ompl::base::MechanicalWorkOptimizationObjective::motionCost` would only return the value of `pathLengthWeight_ * si_->distance(s1, s2)`.

Could you explain how this code calculate the mechanical work? 

Best Regards,
Taa

**Comment by mamoll** [comment]
This is correct. The idea is that you can derive a new optimization objective from this class and override the stateCost method to define a cost landscape. This will be application-specific.
