### ISSUE TITLE
KPIECE Planner Projection Problem

### ISSUE THREAD

**Issue by dbojadzic** [ompl/ompl#689]
Hello,

Recently, I tried to create a KPIECE planner with a projection from my CompoundStateSpace. I followed the examples from:

https://ompl.kavrakilab.org/projections.html and
https://ompl.kavrakilab.org/ConstrainedPlanningImplicitChain_8py_source.html

Everything seems to work fine, however for some reason I can't set the cell sizes correctly. Almost as if the setCellSizes and defaultCellSizes functions are completely ignored.

Here, I create a CompoundStateSpace and assign it a Projection called KSTSimpleProjection inharited from ProjectionEvaluator:

![Screenshot from 2020-01-17 17-19-05](https://user-images.githubusercontent.com/24939584/72628961-afa13a00-394f-11ea-98ca-3801c384bf46.png)

I create a planner and obtain the projection from my StateSpace and assign it to the planner:

![Screenshot from 2020-01-17 17-17-55](https://user-images.githubusercontent.com/24939584/72629020-c6479100-394f-11ea-84b8-a97c42398519.png)

However, Even though I try to change the cell sizes, this is the output of the code:

![Screenshot from 2020-01-17 17-19-34](https://user-images.githubusercontent.com/24939584/72629129-fabb4d00-394f-11ea-906b-b250ed7207df.png)

Neither the code from setCellSizes nor defaultCellSizes seems to influence the size of the cells. However, if I change the code inside getDimension from 2 to 3, the output also gets changed (which means that I have the correct class reference).

Has anyone encountered this problem before and is there a way to fix it? Also, if anyone has any suggestions on how to properly create the projection and use it (without the error or numerical precision warning), please feel free to let me know.

Thank you very much for your help.

**Comment by mamoll** [comment]
I can reproduce the problem. For now, you can use this workaround:
```
pe.setCellSizes(list2vec([.5, .5]))
```
where `list2vec` is this helper function:
```
def list2vec(l):
    ret = ou.vectorDouble()
    for e in l:
        ret.append(e)
    return ret
```
