### ISSUE TITLE
OMPL Gallery Missing Images/Video

### ISSUE THREAD

**Issue by eschneider1992** [ompl/ompl#691]
Not a code bug, just having an issue with accessing the OMPL documentation when trying to check the library out. The gallery page appears to be almost blank. I can see text and headers, but no images or video. The one exception is the bottom-most post, Class Project from COMP 450 on Path Optimization, which has two visible images. Thus far I've tried it on Chrome/Firefox (linux) and Chrome/Safari (mac). Is this happening on your end as well?

https://ompl.kavrakilab.org/gallery.html

**Comment by mamoll** [comment]
Thanks for reporting the issue. The problem is that we link have insecure urls (http rather https) for the videos, so browser refuse to display the content. A simple workaround for now is to visit **http**://ompl.kavrakilab.org/gallery.html instead. I will fix this soon.

**Comment by mamoll** [comment]
Fixed.
