### ISSUE TITLE
Can I inherit ompl::geometric::PathSimplifier and create my own collapseCloseVertices() function

### ISSUE THREAD

**Issue by lusu8892** [ompl/ompl#702]
Hi OMPL

Can I inherit ompl::geometric::PathSimplifier and create my own collapseCloseVertices() function. I have looked classes, like SimpleSetup, PathGeometric and SpaceInformation. None of them has a function that allows me to set a kind of PathSimplifier. I want to use my own defined collapseCloseVertices() function to accommodate with user defined StateSpace. Like I can set my own StateValidityChecker and MotionValidator.

Thanks

**Comment by mamoll** [comment]
There is no `SimpleSetup::setPathSimplifier` method, but you can get the solution path and do whatever you want with it. You don't need to use PathSimplifier.
