### ISSUE TITLE
Graph traversal planners like A*, D* in OMPL

### ISSUE THREAD

**Issue by bagavi** [ompl/ompl#709]
_Context_: OMPL has implemented many sampling-based planners for both geometric and control settings.
_Question_: Are there any implementations of A*, D*, Anytime D* Lite (or it's variant) planners in OMPL or any of its forks?
_Note_: These algorithms are implemented in [SBPL](https://github.com/sbpl/sbpl); is there any way to connect these two libraries

Thanks in advance!

**Comment by mamoll** [comment]
Both libraries used to be supported in MoveIt. OMPL is the default planning library in MoveIt. I am not 100% sure what the status of SBPL support in MoveIt is. You may want to check with the SBPL maintainers.

The OMPL Planner API could easily support A*, D*, etc. If you want to add support for these algorithms, that'd be great.
