### ISSUE TITLE
Implementation of multi-threaded performance test

### ISSUE THREAD

**Issue by lusu8892** [ompl/ompl#714]
Hi OMPL

Recently, I am trying to implement a multi-threaded performance test to my planner. The background is I want to run this planner say, 100 times with 100 pairs of randomly generated valid start state and goal state in a main function. Right now, my test ran very slow because these 100 tests needs to run sequentially. So I am wondering if I can run these 100 tests in parallel fashion by using C++ thread library?

There is one thing to consider is that my local planner, aka MotionValidator, has some parts that implemented multi-thread to do collision check. Is this going to be a problem if I ran performance testing in multi-threading fashion?

I tried to make multi-threaded performance test but running time often got problem, the code shutdown for some reason I do not know.

Since I am a rookie to C++ multi-threading, could you give me some help?

Thanks

**Comment by mamoll** [comment]
OMPL is thread-safe, so you can run multiple planners in parallel. However, for benchmarking this may not be desirable (unless you have a machine with >100 cores).
