### ISSUE TITLE
ompl:x64-windows 1.4.2-3 'localtime' deprecated.  Consider using localtime_s

### ISSUE THREAD

**Issue by gautz** [ompl/ompl#716]
When building my project in VS2017 with latest ompl:x64 release (1.4.2-3), I get following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	Optimal_PathPlanner_IPA	d:\vcpkg\installed\x64-windows\include\ompl\util\time.h	81	
```
OMPL is included with ``vcpkg install ompl:x64-windows``

**Comment by mamoll** [comment]
Since ompl installed successfully with vcpkg, is it possible that the compile settings of your own project are causing this failure? `localtime` may be deprecated, but that should cause a warning, not an error IMO.
