### ISSUE TITLE
Is it possible to achieve the same path result by controlling the seed of sampler?

### ISSUE THREAD

**Issue by ChaochaoLikeNoodles** [ompl/ompl#729]
Hi, I am learning OMPL, thank you for providing such a good library for motion planning. I understand that OMPL uses Sampling-based Motion Planning algorithms, and the because of the sampling process is a random process, even the start and goal states(and other planner parameters) are the same for each run, the path result is different for each run.

But is it possible to achieve the same result for the same start and goal states(and other planner parameters) in each run with OMPL, like set the same seed? But this seed might only affect one sampling step, not all the sampling steps when running an algorithm. Or this is just not possible because of using sampling-based motion planning algorithms? 

Thank you for any feedback.

**Comment by mamoll** [comment]
The random number generators used in OMPL are quasi-random: given the same initial seed, the sequence of 'random' numbers is the same. You can set the global seed with the static member function `ompl::RNG::setSeed(std::uint_fast32_t seed)`. Do this before you do any planning.

This feature is useful for, e.g., debugging, but for performance analysis you should really look at the aggregate performance over many runs.
