### ISSUE TITLE
install-ompl-ubuntu.sh can't get last release 

### ISSUE THREAD

**Issue by JJRedmond** [ompl/ompl#731]
Hi, developers!

I haven't could install OMPL by using install-ompl-ubuntu.sh and have gotten an error

2020-06-17 19:20:58--  https://github.com/ompl/ompl/releases/download/1.5.0/ompl-1.5.0.tar.gz
2020-06-17 19:20:59 ERROR 404: Not Found.

How can I solve it?

Thank you for reply

**Comment by mamoll** [comment]
Thanks for reporting this issue! Please download the script again and try to run it again. With the switch from bitbucket to GitHub the URLs did not get updated correctly. Apologies for the inconvenience.

**Comment by JJRedmond** [comment]
Hi, @mamoll!

Thanks for the answer.
Unfortunately script is not working yet.
The new version give this error:
./install-ompl-ubuntu.sh: line 80: syntax error near unexpected token `else'

**Comment by JJRedmond** [comment]
This changes make it works

        if [ -z $APP ]; then
            wget -O - https://github.com/ompl/${OMPL}/archive/1.5.0.tar.gz | tar zxf -
            cd ${OMPL}**-1.5.0**
        else
            wget -O - https://github.com/ompl/${OMPL}/releases/download/1.5.0/${OMPL}-1.5.0-Source.tar.gz | tar zxf -
            cd $OMPL-1.5.0-Source
        **fi**

**Comment by mamoll** [comment]
That's what I get for trying to fix things quickly. Thanks for the fix.
