### ISSUE TITLE
Loading PRM from PlannerData

### ISSUE THREAD

**Issue by allenc** [ompl/ompl#732]
https://github.com/ompl/ompl/blob/277317b05ecff9e0aab89f044da90f12861a239e/src/ompl/geometric/planners/prm/src/PRM.cpp#L741-L742

It doesn't look like reverse edges are added during PRM roadmap construction, but they're added when getting/loading a roadmap from prior Planner Data. Is this intended?

**Comment by mamoll** [comment]
Yes. The PRM graph is undirected, while the PlannerData graph is directed.
