### ISSUE TITLE
Waypoint Planning with OMPL

### ISSUE THREAD

**Issue by Levi-Armstrong** [ompl/ompl#736]
Does OMPL support the following concept? I have a set of locations and at each location I have a set of joint solutions. I would like to leverage OMPL to find a motion through each location leveraging the available solution to find the optimal path. Obviously I could plan them in series but this may not be the most optimal path for going through all locations since there are multiple solutions at each location.

**Comment by mamoll** [comment]
It doesn't support it out of the box, but if you're using MoveIt, then you could use the MoveIt Task Constructor.

**Comment by Levi-Armstrong** [comment]
Thank you. I will take a look.
