### ISSUE TITLE
Python Bindings: Consider SWIG?

### ISSUE THREAD

**Issue by davidrusu** [ompl/ompl#744]
Hi there, I've been trying to get a build of OMPL with python bindings for the last few days and it's been a struggle.

I am at a point where I'm stepping back to see if there's a different approach, instead of the py++ and castxml toolchain, have you considered SWIG? http://swig.org/

I've seen it used in other libraries with success. I'm wondering what thoughts you have on SWIG and whether you think trying SWIG for generating python bindings could be a good idea.

Take a look at some projects using SWIG here: http://swig.org/projects.html

**Comment by mamoll** [comment]
If we were to switch to SWIG, we'd have to *manually* create/maintain python bindings for everything. The bindings are currently automatically generated, so as the C++ code changes it is not too bad to keep the Python bindings up to date. I agree that the build process is a bit cumbersome. Without more info I can't help you fix your specific build problems. If had to start from scratch today on generating python bindings, I'd probably prefer [Pybind11](https://pybind11.readthedocs.io/en/stable/) / [Binder](https://github.com/RosettaCommons/binder) over py++.
