### ISSUE TITLE
LazyPRM star does not inform the problem definition about its potential solutions

### ISSUE THREAD

**Issue by Hugal31** [ompl/ompl#745]
The LazyPRM tries to find a solution while the termination condition is not true, or if the optimization function is satisfied, and then give the solution to the problem definition ([here](https://github.com/ompl/ompl/blob/master/src/ompl/geometric/planners/prm/src/LazyPRM.cpp#L422)).

However, some termination condition (as the [CostConvergenceTerminationCondition](https://github.com/ompl/ompl/blob/master/src/ompl/base/terminationconditions/CostConvergenceTerminationCondition.h)) needs to have access to the potentials solutions in order to work, via the ProblemDefinition "intermediateSolutionCallback".

It would be great to inform the ProblemDefinition about the current potential solution, for instance [here](https://github.com/ompl/ompl/blob/253e8c0e8d59147be71d33f1a662b933fcac6774/src/ompl/geometric/planners/prm/src/LazyPRM.cpp#L408).

**Comment by zkingston** [comment]
Closing in favor of #745
