### ISSUE TITLE
 Plan problems during simplifySolutions

### ISSUE THREAD

**Issue by akjay** [ompl/ompl#746]
During the plan process,we use such as RRT or RRTConnect algorithm to find a path,after random search,we will do a job named "simplifySolution", it will call function in ompl::geometric::PathSimplifier class to do path simplify work.
In this function, there are many ways to simplify a solution,"shortcutPath" ,"findBetterGoal", "smoothBSpline", "checkAndRepair", etc..Each step means to reduce vertices in the path,and it really makes the path better to be executed.
But there seems a problem that,when we try to reduce a vertex or replace one with new state,we will check whether the state is valid or not,like `checkMotion(state s0, state s1)`,this function will check states interpolate among the s0 and s1,the states count is calculate by function `validSegmentCount`,but in many situation,after the simplifySolution work, the path is been reduced only 3 or 4 states left, however the minimum_waypoint_count is 10,so we need to interpolate again to meet the minimum_waypoint_count requirement.Sometimes,the total `validSegmentCount` between the simplified path states is less than 10,then we need to do a fine interpolate to meet the requirement,but this will generate some states that not checked before,and this may cause a collision when final path check after interpolation,this will cause the path invalid and can not be executed.
So maybe the initial path can work,but after simplify work,the path turned to be invalid.How can we improve simplify work to prevent this happen?Do more check during simplify steps?

I first post this issue in the moveit repository,[#2261](https://github.com/ros-planning/moveit/issues/2261) maybe it's more related with OMPL.

**Comment by mamoll** [comment]
As mentioned in the moveit issue, you probably have to change the `longest_valid_segment_fraction` parameter. If that doesn't solve the problem, feel free to reopen this issue.
