### ISSUE TITLE
Robot manipulator planning

### ISSUE THREAD

**Issue by ndehio** [ompl/ompl#750]
Hi
I would like to use OMPL with a manipulator robot such as Kuka-LWR or Panda based on the urdf format.
Unfortunately, I did not find any example in the demo/tutorial sections.
I prefer not to use MoveIt. Can anyone provide some sample code? This would be really helpful.
best
Niels

**Comment by mamoll** [comment]
OMPL has no notion of kinematics. This is by design. You need a larger robotics software framework (such as MoveIt) to do everything else. OMPL has been integrated with a [variety of other robotics software frameworks](http://ompl.kavrakilab.org/integration.html).
