### ISSUE TITLE
Why are sanity checks handled differently for the Reeds-Shepp state space

### ISSUE THREAD

**Issue by imgeorgiev** [ompl/ompl#758]
Hello

I was playing around with the Reeds-Shepp state space and noticed that it handled sanity checks in particular in a different way than most state spaces:

```cpp
            void sanityChecks() const override
            {
                double zero = std::numeric_limits<double>::epsilon();
                double eps = .1;  // rarely such a large error will occur
                StateSpace::sanityChecks(zero, eps, ~STATESPACE_INTERPOLATION);
            }
```

In particular, the `~STATESPACE_INTERPOLATION` is worrying me as that skips these checks:

1. Interpolation from a state at time 0 should not change the original state
2. Interpolation to a state at time 1 should be the same as the final state
3. Continued interpolation does not work as expected. Please also check that interpolate() works with overlapping memory for its state arguments

I understand that point (3) needs to be disabled due to the nature of the distance function (see below) but points (1) and (2) should still be valid sanity checks for the Reeds Shepp state space. Is there something I am missing here, or should the sanity checks be modified to have more granularity?

PS. 
Why point (3) doesn't hold for Reeds-Shepp state space. Let's say that the notation (s1 -> s2) * t interpolates the path from state s1 to state s2 and selects the state that is t*100% through the interpolated path. OMPL does the sanity check:
s3 = (s1 -> s2) * 0.75
must be equal to
s5 = (s4 -> s1) * 0.25
where s4 = (s1 -> s2) * 1.0 

However, this sanity check is not valid for ompl as the distance (or Reeds-Shepp path) is different between s1 -> s2 and s4 -> s1. I realize that this is a lackluster explanation for those that are not familiar with the Reeds-Shepp state space but I don't think I can do better right now.

**Comment by zkingston** [comment]
There could be more refined flags for `sanityChecks` that separates start/end interpolation with continuous interpolation, but `sanityChecks` are more for those implementing a custom state space who may not realize that they have introduced unintended behavior to their state space. We would welcome more refined / additional sanity checks if they made sense.
