### ISSUE TITLE
Updated tag release with PR #759?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ompl/ompl#765]
I spoke with the Microsoft ROS team about getting the latest fixes to the CMake config in the Windows ROS release and they stated that they need a tag release that includes these changes. What are your thoughts on creating a tag with the latest fix to CMake Config?

**Comment by mamoll** [comment]
I will create a OMPL 1.5.1 release based on current master.

**Comment by Levi-Armstrong** [comment]
Thank you.
