### ISSUE TITLE
Cannot build v1.4.2 on macOS with boost 1.74

### ISSUE THREAD

**Issue by mengyu-fu** [ompl/ompl#767]
I am trying to build version 1.4.2 on MacBook, my boost is installed with homebrew and the latest version is 1.74. I got the following error message:

In file included from /Users/travis/build/mengyu-fu/iris/external/ompl/demos/PlannerData.cpp:45:
/usr/local/include/boost/graph/astar_search.hpp:433:75: error: non-const lvalue reference to type 'boost::dummy_property_map' cannot bind to a value of unrelated type 'boost::astar_visitor<boost::null_visitor>'
        boost::graph::keywords::tag::visitor, dummy_property_map& >::type vis
                                                                          ^
/Users/travis/build/mengyu-fu/iris/external/ompl/demos/PlannerData.cpp:173:16: note: in instantiation of function template specialization 'boost::astar_search<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<vertex_type_t, ompl::base::PlannerDataVertex *, boost::property<boost::vertex_index_t, unsigned int, boost::no_property> >, boost::property<edge_type_t, ompl::base::PlannerDataEdge *, boost::property<boost::edge_weight_t, ompl::base::Cost, boost::no_property> >, boost::no_property, boost::listS>, (lambda at /Users/travis/build/mengyu-fu/iris/external/ompl/demos/PlannerData.cpp:174:13), ompl::base::Cost, boost::distance_zero_t, boost::bgl_named_params<ompl::base::Cost, boost::distance_inf_t, boost::bgl_named_params<(lambda at /Users/travis/build/mengyu-fu/iris/external/ompl/demos/PlannerData.cpp:177:30), boost::distance_combine_t, boost::bgl_named_params<(lambda at /Users/travis/build/mengyu-fu/iris/external/ompl/demos/PlannerData.cpp:176:30), boost::distance_compare_t, boost::bgl_named_params<boost::vector_property_map<unsigned long, boost::typed_identity_property_map<unsigned long> >, boost::vertex_predecessor_t, boost::no_property> > > > >' requested here
        boost::astar_search(graph, start,
               ^
1 error generated.
make[2]: *** [demos/CMakeFiles/demo_PlannerData.dir/PlannerData.cpp.o] Error 1
make[1]: *** [demos/CMakeFiles/demo_PlannerData.dir/all] Error 2
make: *** [all] Error 2

Thanks!

**Comment by mamoll** [comment]
This should be fixed in later versions of OMPL, 1.5.0 and 1.5.1. This is the fix for the specific error you're seeing:

```diff
diff --git a/demos/PlannerData.cpp b/demos/PlannerData.cpp
index 109338bd..8802b7e8 100644
--- a/demos/PlannerData.cpp
+++ b/demos/PlannerData.cpp
@@ -170,13 +170,15 @@ void readPlannerData()
         ob::GoalState goal(si);
         goal.setState(data.getGoalVertex(0).getState());
         ob::PlannerData::Graph::Vertex start = boost::vertex(data.getStartIndex(0), graph);
+        boost::astar_visitor<boost::null_visitor> dummy_visitor;
         boost::astar_search(graph, start,
             [&goal, &opt, &vertices](ob::PlannerData::Graph::Vertex v1) { return distanceHeuristic(v1, &goal, &opt, vertices); },
             boost::predecessor_map(prev).
             distance_compare([&opt](ob::Cost c1, ob::Cost c2) { return opt.isCostBetterThan(c1, c2); }).
             distance_combine([&opt](ob::Cost c1, ob::Cost c2) { return opt.combineCosts(c1, c2); }).
             distance_inf(opt.infiniteCost()).
-            distance_zero(opt.identityCost()));
+            distance_zero(opt.identityCost()).
+            visitor(dummy_visitor));
 
         // Extracting the path
         og::PathGeometric path(si);
```
