### ISSUE TITLE
when I execute OMPL_APP.PY on terminal it gives me this error. I install library of util but this not resolves.

### ISSUE THREAD

**Issue by SundasMujahid** [ompl/ompl#769]
![issue](https://user-images.githubusercontent.com/56893483/102695939-80283b00-424c-11eb-9cdc-7dd162994979.PNG)
I installed Ubuntu 18 and python 2.7

**Comment by lpmrz** [comment]
I have the same problem too.

**Comment by SundasMujahid** [comment]
> I have the same problem too. Did you manage to solve it?

No

**Comment by mamoll** [comment]
This error means that there was an error in generating or compiling the python bindings. Are you sure you completed all the build steps?

**Comment by lpmrz** [comment]
I solved it when I compiled everything from the scratch. Thank you for your reply.
