### ISSUE TITLE
OMPL app visualization issue

### ISSUE THREAD

**Issue by miranisaurabh** [ompl/ompl#781]
I was trying to visualize paths using .txt files for the Home environment and noticed that the start and goal happen to be different than expected. 
Example path:
```
0.0 -145.03 70.2 0.227138573674 -0.307113663148 0.366266006751 0.848491884791
0.0 -145.03 70.2 0.227138573674 -0.307113663148 0.366266006751 0.848491884791
0.0 -145.03 70.2 0.227138573674 -0.307113663148 0.366266006751 0.848491884791
```
I expect just one single point in SE3 but observed two points (see below)
![image](https://user-images.githubusercontent.com/16609826/109628622-d0970100-7af7-11eb-88d3-cc916aad29d9.png)

After digging into the source code and visualizing I found out that Start and Goal poses are in ZYX Euler format and the path is in XYZ Euler format.
See the difference in Start and Goal below in the Problem window: It's just ZYX->XYZ
![image](https://user-images.githubusercontent.com/16609826/109628536-b52bf600-7af7-11eb-87b2-3b79b1b590cc.png)

**Comment by YuhengZhi** [comment]
I can confirm this problem and can reproduce the above bug using the openPath API.

**Comment by YuhengZhi** [comment]
[This (simple) pull request](https://github.com/ompl/omplapp/pull/7) should address it.

**Comment by mamoll** [comment]
Fixed by merging @YuhengZhi's PR in the omplapp repo.
