### ISSUE TITLE
error when reference ompl library in windows

### ISSUE THREAD

**Issue by radeonwu** [ompl/ompl#782]
I am facing the following LNK2001 error, when creating a C++ console app that references ompl library in windows environment. 
...
1>ompl.lib(StateSpace.cpp.obj) : error LNK2001: unresolved external symbol __imp____std_init_once_begin_initialize@16
1>ompl.lib(RandomNumbers.cpp.obj) : error LNK2001: unresolved external symbol __imp____std_init_once_begin_initialize@16
1>ompl.lib(StateSpace.cpp.obj) : error LNK2001: unresolved external symbol __imp____std_init_once_complete@12
1>ompl.lib(RandomNumbers.cpp.obj) : error LNK2001: unresolved external symbol __imp____std_init_once_complete@12
1>ompl.lib(PathGeometric.cpp.obj) : error LNK2001: unresolved external symbol ___std_reverse_trivially_swappable_4
...

My project and environment info:
- Windows 10
- visual studio 2015 
- installed ompl library through vcpkg tool
- tried reference ompl via both dynamic and static library format, and the same error happens

Your suggestions are appreciated.

**Comment by QH-Liang** [comment]
I've met the same problem. 
It seems that your Visual studio had a update. In stackoverflow, someone met the similar problem when using OpenGL.

Microsoft said:
"When you upgrade to a new version of Visual Studio, you might encounter compilation and/or runtime errors in code that previously compiled and ran correctly. Changes in the new version that cause such problems are known as breaking changes, and typically they're required by modifications in the C++ language standard, function signatures, or the layout of objects in memory."
And they recommend:
"To avoid run-time errors that are difficult to detect and diagnose, we recommend that you never statically link to binaries compiled by using a different version of the compiler."

original link:
https://msdn.microsoft.com/en-us/library/bb531344.aspx

I found that when you build ompl by default settings using vcpkg, the program will link the static lib. Meanwhile, I can't find the shared lib "dll" in vcpkg dir. 

so, I think if you remove the ompl by using vcpkg command and rebuild the ompl, the problem can be solved.
@radeonwu @rojkov
