### ISSUE TITLE
Plannerarena unable to download plot as RData

### ISSUE THREAD

**Issue by captain-yoshi** [ompl/ompl#787]
When I try to download a plot as RData from the Overall performance tab, it fails. It looks like a server problem (see image below).

![image](https://user-images.githubusercontent.com/32679594/110171893-649feb80-7dca-11eb-955a-6bc447d07d79.png)

**Comment by mamoll** [comment]
Fixed in c76dab2936410b586bb1a5e61dd72363573703fb. Thanks for reporting this!
