### ISSUE TITLE
New planner

### ISSUE THREAD

**Issue by SundasMujahid** [ompl/ompl#794]
Hello, I want to add a new planner in ompl. I just added header and cpp file in geometric.  And include header file of new planner in
 ompl/py-bindings/headers_geometric.txt

Now plz tell me other then above what else should I add and in which file? 

Also after adding this how I can generate python bindings through which command?
Bcz it takes 2 days for python bindings and after compiling two days new planner is not added.
Plz tell me here simple method briefly. 
Thanks in advance!!

**Comment by mamoll** [comment]
Please look at the [documentation for generating python bindings for a new planner](https://ompl.kavrakilab.org/pybindingsPlanner.html) and the [notes about regenerating bindings](https://ompl.kavrakilab.org/python.html#updating_python_bindings). This is an advanced topic. You will likely have to read up on how cmake, Py++, and Boost.Python work if things don't work right away.
