### ISSUE TITLE
OMPL NEW PLANNER ISSUE

### ISSUE THREAD

**Issue by SundasMujahid** [ompl/ompl#795]
Hello, I have some implementation issues when adding the planner.

when I'm adding a new planner in ompl by following this link,

https://ompl.kavrakilab.org/pybindingsPlanner.html

Procedure:
I added header and cpp file in geometric planner. I just copy the rrtstar header and cpp code and paste it in new file named as "rrtstarx". To check that planner is added to not.

Then I add header file in gemetric.txt after rrtstar header file.

After that I go in build directory and in release I open a terminal and run the make clean_bindings and then make -j 3 update_bindings. 
But after updating when I open gui the new planner is not added there. It is not showing on interface. 

I tried looking into the pyplusplus_geometric.log at omplapp/build/Release, but there I could not find anything regarding the new planners and they don’t show up in the build-folder anywhere.

What do I have to do to create fitting python-bindings?
I attached the planner-headers, headers_geometric and the pypluplus_geometric.log.

I use Ubuntu 16.4.6 and have libspot installed.

I'm waiting for your positive response.
Regards!!!

**Comment by zkingston** [comment]
Closing this issue due to age. If you are still interested, please post the relevant files to your issue.
