### ISSUE TITLE
the binary's not including  ompl/base/Constraint.h 

### ISSUE THREAD

**Issue by avielTevel** [ompl/ompl#798]
I installed the binary in my ubuntu and I can't reach ompl/base/Constraint.h  file.
did something happen with the build?

**Comment by mamoll** [comment]
Which version of Ubuntu and OMPL do you have?

**Comment by avielTevel** [comment]
ubuntu bionic
i use 
apt-get install libompl-dev ompl-demos
so probably the newest one..

**Comment by mamoll** [comment]
The version in apt for bionic is OMPL 1.2. This is not the latest version and does not contain the constrained planning code. You can [build the latest OMPL from source](http://ompl.kavrakilab.org/installation.html).
