### ISSUE TITLE
Cannot install ompl for python2.7

### ISSUE THREAD

**Issue by NayOoLwin5** [ompl/ompl#803]
My OS is Ubuntu 18.04. I have successfully installed ompl-1.5.2 for python3.6 (default for my OS) using the installation script.
But I want to install ompl-1.5.2 for python2.7 because I am working with ROS-Melodic which comes with python2.7.
So I changed ```PYTHONV=3``` to ```PYTHONV=2``` before the line that reads `install_common_dependencies` in the installation script. Now, running ```./install-ompl-ubuntu.sh --python``` gives me this error -
```
E: Unable to locate package python2-dev
E: Unable to locate package python2-pip
```
How do I solve this issue?

**Comment by mamoll** [comment]
Can you set PYTHONV to be empty? That is, `PYTHONV=''`.
