### ISSUE TITLE
fatal error: ompl/config.h: No such file or directory compilation terminated

### ISSUE THREAD

**Issue by Prajwalmj** [ompl/ompl#814]
* Hi, I was trying to run a simple code to check working of ompl library. After installing, I tried to run my code, but got this error.
* Below images attached shows the error, I am confused between "config.h" and "config.h.in" files, I am aware that .h.in files are used for configure scripts, but still don't understand why I am getting this error
![git_ompl](https://user-images.githubusercontent.com/37709186/123851120-d73c5600-d8e8-11eb-8696-25a8e8f43a62.png)
![git_ompl_2](https://user-images.githubusercontent.com/37709186/123851125-d99eb000-d8e8-11eb-9917-5a665d7ed385.png)
* Please let me know how to solve this issue, or if I am doing something wrong here.

**Comment by zkingston** [comment]
'config.h' will only appear in the **built** OMPL include directory, not within the source of OMPL. Once you've built and installed OMPL (either through the [install script](http://ompl.kavrakilab.org/installation.html) or manually), you can get the relevant compiler flags necessary using `pkg-config`, e.g., ‘pkg-config --cflags ompl‘. Also, in the future I'd recommend using something like cmake to help build your code.
