### ISSUE TITLE
unable to install omplapp

### ISSUE THREAD

**Issue by AbhinayNS** [ompl/ompl#815]
Hi, 
I have been trying to install omplapp by running ./install-ompl-ubuntu.sh --github --app command
I am using a system ubuntu16.04 and python2.7
First I got a issue saying libspot and spot libraries not found, i solved that by installing spot while disabling the python bindings for spot 
I still get cmake errors when i run the command cmake ../.. -DPYTHON_EXEC=/usr/bin/python 
The full output of this command is given below 

cmake ../.. -DPYTHON_EXEC=/usr/bin/python

-- Build type: Release
-- Found Python: /usr/lib/x86_64-linux-gnu/libpython2.7.so  
-- Code for module base not found; type "make update_bindings"
-- Code for module control not found; type "make update_bindings"
-- Code for module geometric not found; type "make update_bindings"
-- Code for module tools not found; type "make update_bindings"

-- Code for module app not found; type "make update_bindings"
-- 
-- The following features have been enabled:

 * OMPL_VERSIONED_INSTALL , Whether to install header files in
   <prefix>/include/ompl-X.Y/ompl, where X and Y are the major and minor
   version numbers
 * OMPL_BUILD_PYBINDINGS , Whether to build the Python bindings.
 * OMPL_BUILD_PYTESTS , Whether to build/run the python binding unit tests.
 * OMPL_BUILD_TESTS , Whether to build the unit tests.
 * OMPL_BUILD_DEMOS , Whether to build the OMPL demo programs.

-- The following OPTIONAL packages have been found:

 * OpenGL , <http://opengl.org>
   Used to render graphics in ompl_app.
 * flann (required version >= 1.8.3) , <https://github.com/mariusmuja/flann>
   If detetected, FLANN can be used for nearest neighbor queries by OMPL.
 * spot , <http://spot.lrde.epita.fr>
   Used for constructing finite automata from LTL formulae.
 * ODE , <http://ode.org>
   The Open Dynamics Engine can be used as a "black box" for kinodynamic planning.
 * octomap
 * Threads , <https://en.wikipedia.org/wiki/POSIX_Threads>
   Pthreads is sometimes needed, depending on OS / compiler.
 * Doxygen , <http://doxygen.org>
   Used to create the OMPL documentation (i.e., http://ompl.kavrakilab.org).
 * PkgConfig , <https://www.freedesktop.org/wiki/Software/pkg-config/>
   Used to find (compilation flags for) dependencies.
 * yaml-cpp , <https://github.com/jbeder/yaml-cpp>
   Used for parsing input data for the PlanarManipulator demo.
 * Python , <http://python.org>
   Used for python bindings.
 * castxml , <https://github.com/CastXML/CastXML>
   Used to generate Python bindings.

-- The following REQUIRED packages have been found:

 * Eigen3 , <http://eigen.tuxfamily.org>
   A linear algebra library used throughout OMPL.
 * assimp , <http://assimp.org>
   Used in ompl_app for reading meshes representing robots and environments.
 * ccd , <https://github.com/danfis/libccd>
   Collision detection library used by fcl.
 * fcl , <https://github.com/flexible-collision-library/fcl>
   The default collision checking library.
 * Boost , <http://boost.org>
   Used throughout OMPL for data serialization, graphs, etc.

-- The following OPTIONAL packages have not been found:

 * pypy , <http://pypy.org>
   Used to speed up the generation of python bindings.
 * Triangle , <http://www.cs.cmu.edu/~quake/triangle.html>
   Used to create triangular decompositions of polygonal 2D environments.
 * MORSE , <https://www.openrobots.org/wiki/morse>
   OMPL includes a plugin for the MORSE Robot Simulation engine.
 * Drawstuff , <http://ode.org>
   Part of the ODE source distribution, used in one demo program.
 * PQP , <http://gamma.cs.unc.edu/SSV/>
   Used as an alternative, additional collision checking library (the default is FCL).

-- The following Python modules were found:

 * PyQt5 OpenGL pyplusplus pygccxml flask celery

-- Configuring done
CMake Error at src/omplapp/CMakeLists.txt:23 (add_library):
  Target "ompl_app" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/omplapp/CMakeLists.txt:23 (add_library):
  Target "ompl_app_base" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/omplapp/CMakeLists.txt:23 (add_library):
  Target "ompl_app" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/omplapp/CMakeLists.txt:23 (add_library):
  Target "ompl_app_base" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_AnytimePathShortening" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:20 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE2RigidBodyPlanning" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:12 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE3RigidBodyPlanningWithOptimization" links to target
  "Eigen3::Eigen" but the target was not found.  Perhaps a find_package()
  call is missing for an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:11 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_CollisionCheckers" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:19 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE3RigidBodyPlanningBenchmark" links to target "Eigen3::Eigen"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:9 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_KinematicCarPlanning" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:13 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_DynamicCarPlanning" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:14 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE3RigidBodyPlanning" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:10 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_QuadrotorPlanning" links to target "Eigen3::Eigen" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:16 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE2MultiRigidBodyPlanning" links to target "Eigen3::Eigen" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:17 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_BlimpPlanning" links to target "Eigen3::Eigen" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:15 (add_omplapp_demo)

CMake Error at demos/CMakeLists.txt:5 (add_executable):
  Target "demo_SE3MultiRigidBodyPlanning" links to target "Eigen3::Eigen" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  demos/CMakeLists.txt:18 (add_omplapp_demo)

CMake Error at benchmark/CMakeLists.txt:1 (add_executable):
  Target "ompl_benchmark" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at benchmark/CMakeLists.txt:1 (add_executable):
  Target "ompl_benchmark" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/abhinay/Downloads/omplapp/build/Release

**Comment by zkingston** [comment]
We don't plan on supporting Ubuntu 16.04 - if you need to compile on older machines, you can edit the CMake to use the older target.
