### ISSUE TITLE
Python bindings for XXL

### ISSUE THREAD

**Issue by tejalbarnwal** [ompl/ompl#816]
I tried creating python bindings for XXL planner using the process stated here- https://ompl.kavrakilab.org/pybindingsPlanner.html.
According to this, I added the following two lines in the second last line of ompl/py-bindings/headers_geometric.txt
`src/ompl/geometric/planners/xxl/XXLDecomposition.h`
`src/ompl/geometric/planners/xxl/XXL.h`

Further executed the commands for regenerating python bindings from the build directory.

After doing this, I tried following commands in the Python prompt
`from ompl import geometric`
`dir(geometric)`

But I couldn't find XXL in the list.

**Comment by mamoll** [comment]
It's nontrivial to create python bindings for XXL. We welcome PRs to address this, but I don't consider this a bug.
