### ISSUE TITLE
Make OMPL Installable Via Pip?

### ISSUE THREAD

**Issue by fishbotics** [ompl/ompl#818]
Hi all,

Has there been any discussion about whether it would be possible to make OMPL with Python bindings installable via Pip? The install scripts are already easy, but within a Python project, it makes it hard to manage dependencies. 

I'm sure lots of people would be very excited about having this installable from Pypi and I'd be happy to help!

[EDIT] I should add that part of the reason this would be great is that I develop projects using non-system Python versions. For many ROS-independent applications, such as deep learning, you don't typically use the system Python and sometimes install inside a virtual environment. Right now, the install script relies heavily on the system python and, from what I can tell, the CMake configuration uses the system Python as well. I think it would be _super_ useful to be able to use OMPL independent of this.

Right now, I get around these issues by building inside a docker container where I define the system Python, but that has its own limitations.

**Comment by mamoll** [comment]
This would be nice to have, but it is already hard enough to keep the Python bindings working correctly for different operating systems, compilers, dependency versions. I will not take this on, but if you want to create an OMPL package on PyPI, go ahead.
