### ISSUE TITLE
Missing ODE export on macOS

### ISSUE THREAD

**Issue by henningkayser** [ompl/ompl#824]
OMPL requires explicit linking of the library directories `${OMPL_LIBRARY_DIRS}` on macOS, otherwise ODE is not being linked correctly. See [here](https://github.com/ros-planning/moveit2/pull/549/files#r666785610) for the workaround in MoveIt. I have briefly skimmed the CMakeLists but haven't seen anything suspicious.

**Comment by zkingston** [comment]
#1050 has removed ODE as a dependency, closing.
