### ISSUE TITLE
What does MechanicalWorkOptimizationObjective do?

### ISSUE THREAD

**Issue by werner291** [ompl/ompl#828]
Hello,

I'm currently looking into whether TRRT and BiTRRT could prove useful in the problem I'm working on, but I'm confused about how the `MechanicalWorkOptimizationObjective` is defined.

Namely: https://github.com/ompl/ompl/blob/main/src/ompl/base/objectives/src/MechanicalWorkOptimizationObjective.cpp#L59

which, since state cost is always 1 (https://github.com/ompl/ompl/blob/main/src/ompl/base/objectives/src/MechanicalWorkOptimizationObjective.cpp#L51) appears to essentially just collapse into optimizing for path length?

Am I misunderstanding this?

**Comment by werner291** [comment]
Never mind, I think my confusion stems from how these objectives are used in MoveIt; this implementation makes total sense if the objective gets subclassed.

**Comment by MarcM0** [comment]
Wait so is it actually any different? Does it minimize joint movement?
