### ISSUE TITLE
Not enforcing max distance when valid but longer path to the goal state is available

### ISSUE THREAD

**Issue by krakjack5** [ompl/ompl#834]
I am currently experimenting with OMPL and as such I am a new user. Thank you very much to all who have made such a wonderful library available to users.

I am using RRT to plan paths with Dubins curves and it is working well. The scenario I am experimenting with is as follows. There are a number of obstacles near the start state; however after those obstacles are cleared, the goal state is in a large area without any obstacles. I limit the planner range (max distance between two adjacent states), to achieve less wavy paths. The planner samples the goal state once in a while depending on the goal bias value. Even if there exists a valid motion/path to the goal state from the nearest state in the tree, albeit longer than the max distance (planner range), the planner still truncates it to the max distance. In many situations, depending on the problem, it may be reasonable to accept the path from the nearest state to the goal state even if it is longer than the planner range. That will also greatly speed up finding the solution, and may be of interest for online path planning. However, going through the code it looks like the planner always enforces the max distance bound even when there exists a valid path to the goal state. Is there any way to instruct the planner to not truncate a valid path to the goal state from the current state even if it is longer than the max distance (planner range)? Thank you very much for your help!

**Comment by zkingston** [comment]
Planning directly to the goal would be similar to the RRTConnect heuristic - works well in practice for many problems, but not necessarily every problem.
