### ISSUE TITLE
Parallel plan planning termination condition is shared across all planners.

### ISSUE THREAD

**Issue by olzhas** [ompl/ompl#845]
Hello,
I found a bug or maybe a feature in ompl::tools::ParallelPlan. If a user creates an object with some kind of ompl::base::PlannerTerminationCondition and passes it to ompl::tools::ParallelPlan::solve() then this termination condition object will be shared across all planners in ParallelPlan.

https://github.com/ompl/ompl/blob/528f02cdc5ac785ba24e1dbdf1cf621a17020b7b/src/ompl/tools/multiplan/src/ParallelPlan.cpp#L105
https://github.com/ompl/ompl/blob/528f02cdc5ac785ba24e1dbdf1cf621a17020b7b/src/ompl/tools/multiplan/src/ParallelPlan.cpp#L111

I am not sure how to fix this at the moment.

**Comment by zkingston** [comment]
I would call this a convenience feature, not a bug. The ParallelPlan utility handles typical use-cases (e.g., timed termination conditions, which is the standard) but I can imagine cases where you would want different conditions for each planner (e.g., iteration counters), but this is fairly advanced usage. If this is the case, I'd recommend either augmenting ParallelPlan yourself (e.g., adding an API that takes a vector of termination conditions) or manually running your planners in parallel. I'm not sure what an API would look like to handle the general case of unique PTCs for each planner in parallel (maybe an allocator?).
