### ISSUE TITLE
Python argument types in ProblemDefinition.setStartAndGoalStates(ProblemDefinition, numpy.ndarray, numpy.ndarray)

### ISSUE THREAD

**Issue by WangCH69** [ompl/ompl#847]
I was trying to embed the ompl path planning algorithm in another program. The original template I used is "OptimalPlanning.py" from official demos.
However, this error occurred when assigning the states of the start-point and goal-point (both are float-type arrays) in function setStartAndGoalStates(start, goal) :

" Boost.Python.ArgumentError: Python argument types in
    ProblemDefinition.setStartAndGoalStates(ProblemDefinition, numpy.ndarray, numpy.ndarray)
did not match C++ signature:
    setStartAndGoalStates(ompl::base::ProblemDefinition {lvalue}, ompl::base::ScopedState<ompl::base::StateSpace> start, ompl::base::ScopedState<ompl::base::StateSpace> goal, double threshold=2.220446049250313e-16)
    setStartAndGoalStates(ompl::base::ProblemDefinition {lvalue}, ompl::base::State const* start, ompl::base::State const* goal, double threshold=2.220446049250313e-16) "

I suppose the problem lies in the difference of data type between python and C++, as the original function defined in C++ file requires double-type number and I can only use float-type number in python when importing that function through py-bindings.
But how am I supposed to use double-type data in python? Or maybe I've got it wrong? Could someone please help me with this one?

**Comment by mamoll** [comment]
Please look at some of the Python demos included with OMPL for examples on how to properly allocate and initialize states of the right type. There is no automatic conversion of numpy types to OMPL data types.
