### ISSUE TITLE
how to convert a 3d numpy array to a obstacle map in 3d space?

### ISSUE THREAD

**Issue by muk465** [ompl/ompl#850]
I have a 3d numpy image aray with different labels , i want to make these labels as  obstacles into ompl state space how can i do that ?
I am doing this w.r.t Rigidbody planning.py( but in  3d)

**Comment by zkingston** [comment]
OMPL does not directly support any robot models that you might have. You will have to write your own state validity checker for the space you want to consider (please see [the tutorial](http://ompl.kavrakilab.org/stateValidation.html)) - this is `isStateValid` in the Python tutorial you reference.
