### ISSUE TITLE
Problem with the validity of the paths found by ABIT* algorithm in my own program

### ISSUE THREAD

**Issue by WangCH69** [ompl/ompl#855]
I was trying to embed the ABIT* algorithm into my own motion planning project, and I used the demo 'OptimalPlanning.py'  as template. I kept all other things unchanged and the only difference in my version is the part of state-validity-check. I've altered it with my self-defined functions to satisfy complicated obstacle-rich 2-D environment.

However one major problem frequently occured when running the new program. Here's what happened: all the points sampled by the ABIT* algorithm are valid, but some paths between certain consecutive points have interference with the obstacle.

This has beening bothering me for a while and I still couldn't figure it out. Isn't the algorithm supposed to do the validity checking of the path？Or is there anything I need to pay attention to run this checking manually?

**Comment by zkingston** [comment]
Could you provide a concrete example of this behavior that is specific to ABIT*? It is normal in certain cases for some edges of a sampling-based algorithm to be invalid if, say, the validity checking resolution is not fine enough for the obstacle geometry (which can be changed with setLongestValidSegmentFraction() on the state space).

**Comment by WangCH69** [comment]
> Could you provide a concrete example of this behavior that is specific to ABIT*? It is normal in certain cases for some edges of a sampling-based algorithm to be invalid if, say, the validity checking resolution is not fine enough for the obstacle geometry (which can be changed with setLongestValidSegmentFraction() on the state space).

Thanks for replying! But I am afraid github dosen't support uploading figures here. 

Here's the detail situation: The self-defined obstacles are all triangles, I set the runtime of solving to 0.17(seconds) and ABIT*found a solution consisting of 8 points. All paths are valid except the one connecting point No.6 and No.7, as it has very clear interference with one triangle obstacle (very close to one of its angle).

Anyway I will try setLongestValidSegmentFraction() first and see whether that would help with the problem. Thanks again!
