### ISSUE TITLE
Catch exceptions in ParallelPlan::solveMore

### ISSUE THREAD

**Issue by simonschmeisser** [ompl/ompl#856]
https://github.com/ompl/ompl/blob/528f02cdc5ac785ba24e1dbdf1cf621a17020b7b/src/ompl/tools/multiplan/src/ParallelPlan.cpp#L168

relates to https://github.com/ros-planning/moveit/issues/3003

MoveIt throws an exception here if it fails to sample to more goals. This is not cached and crashes my application. My understanding is that Exceptions should be handled inside `std::thread`

**Comment by mamoll** [comment]
Solved by merging PR #857
