### ISSUE TITLE
How do i print/get nearest neigbours for my control based rrt problem?

### ISSUE THREAD

**Issue by muk465** [ompl/ompl#869]
si = ss.getSpaceInformation()
planner = oc.RRT(si)
df3=planner.getPlannerProgressProperties()
df4=planner.getPlannerData()

I am not getting any values by using above df3 and df4, also what should be the arguments for getPlannerData() its showing error?

**Comment by zkingston** [comment]
See the [planner data demo](https://ompl.kavrakilab.org/PlannerData_8py_source.html) for Python.
