### ISSUE TITLE
Using a custom valid state sampler doesn't work with LazyPRM and LazyPRMStar

### ISSUE THREAD

**Issue by alimaiem** [ompl/ompl#870]
Hello,

I was trying to use a custom valid state sampler (class MyValidStateSampler : public ompl::base::ValidStateSampler) with a LazyPRMStar planner. The sample method is never called, while using a PRM planner it worked fine. Is this expected?

Thanks,

**Comment by zkingston** [comment]
LazyPRM "lazily" evaluates state/edge validity - it uses a regular state sampler (that is, not a ValidStateSampler) and then checks for collision only once a potential path is found.
