### ISSUE TITLE
Seeding StateSampler::rng_

### ISSUE THREAD

**Issue by alimaiem** [ompl/ompl#871]
Hello,

Is there a way to use your own seed for StateSampler::rng_? This is particularly critical in our application, where we need to have the same result each time we solve the same problem...

Thanks,

**Comment by mamoll** [comment]
See the documentation for the `RNG::setLocalSeed` and `RNG::setSeed` methods [here](http://ompl.kavrakilab.org/classompl_1_1RNG.html).

**Comment by alimaiem** [comment]
Thanks for your feedback.
I know about the documentation for RNG. My question is more about how to access StateSampler::rng_ in order to seed it.
Looking more at the doc, I think I just need to use a deterministic sate sampler?
