### ISSUE TITLE
Warning: ompl::base::AtlasStateSpace::sampleUniform(): Took too long

### ISSUE THREAD

**Issue by arjung128** [ompl/ompl#892]
Hello,

I am trying to implement constrained motion planning, where the constraint is that the end-effector should be close to a line defined by `y=target_y_coord ` and `z=target_z_coord`. I am using `ob.TangentBundleStateSpace(space, constraints)` as my constraint space. The following is my implementation of `constraint.function()`:

```
y_err = (ee_y_coord - target_y_coord)**2
z_err = (ee_z_coord - target_z_coord)**2
out[0] = (y_err + z_err)**0.5
```

However, this seems to be too slow. I am repeatedly getting the following warning, and not getting a valid solution:

```
Warning: ompl::base::AtlasStateSpace::sampleUniform(): Took too long; returning center of a random chart.
         at line 86 in /ompl/base/spaces/constraint/src/AtlasStateSpace.cpp
```

Note that I am able to get a valid solution if I simply replace the `out[0] = (y_err + z_err)**0.5` line with `out[0] = y_err`. 

Additionally, I tried setting the `rho` and `exploration` parameters to be very small (as recommended on line 86 of the documentation [here](https://ompl.kavrakilab.org/AtlasStateSpace_8cpp_source.html)), specifically `rho=1e-5` and `exploration=1e-5`, but I'm still getting this warning and no solution. Is there anything I can do to resolve this issue?

Any help will be much appreciated, thanks in advance!

Edit: I have not implemented the Jacobian just yet, and am implicitly using a numerical Jacobian. Could implementing an analytical Jacobian help resolve this issue?

**Comment by zkingston** [comment]
Implementing an analytical Jacobian will definitely help. This error message implies that the chart projection function (psi) is failing consistently, which could be due to bad approximation from the numerical Jacobian.
