### ISSUE TITLE
RRT / RRT* does not use ValidStateSampler

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ompl/ompl#893]
**Problem Description**
I am currently implementing a RRT planner in [Dubins Airplane](https://ieeexplore.ieee.org/document/4434966) space.

One problem I am trying to solve is to plan a path on terrain under certain altitude constraints. While this works quite well by doing state validity checks, I was wondering if I can do even better by using a `ValidStateSampler`.

I have tried to use RRT/RRT* and allocate a `ValidStateSampler` in order to sample only from the valid space that satisfies altitude constriants. However, although I can allocate the `ValidStateSampler`, RRT does not seem to use the `ValidStateSampler` at all and uses the `StateSampler`.

Is there a specific reason why RRT does not use a `ValidStateSampler` even if it is allocated? or is this just a matter of extending the RRT to use the valid state sampler?

Thanks!

**Comment by ChamzasKonstantinos** [comment]
Hi @Jaeyoung-Lim, yes `RRT` and most Tree-Based planners  do not use the `ValidStateSampler` and that is on purpose. The sampling part of RRT only helps it choose the direction to expand towards to, it does not necessarily need to be a valid sample.
For example you can sample on invalid point on an obstacle and the tree will expand towards that obstacle. If you want to override the Samplers to bias your sampling you can directly override the `StateSampler` you don't need the `ValidStateSampler'.

**Comment by mamoll** [comment]
The choice between ValidStateSampler or StateSampler is not a matter of personal preference, but often an important part of the algorithm design. However, nothing stops you from implementing a StateSampler-derived class that only samples valid samples. You can then call `ompl::base::StateSpace::setStateSamplerAllocator` with a functor that allocates instances of your state sampler. (This also means your state validity checker could be simplified to simply always return `true`.)

**Comment by Jaeyoung-Lim** [comment]
@mamoll @ChamzasKonstantinos Thanks for the clarification!

**Comment by mamoll** [comment]
Actually, what I wrote about the validity checker is incorrect. This will also be checked by the motion validator, which by default calls the validity checker on interpolated states, which may not be valid.
