### ISSUE TITLE
ompl::base::AtlasStateSpace::anchorChart(): Initial chart creation failed. Cannot proceed.

### ISSUE THREAD

**Issue by arjung128** [ompl/ompl#894]
Hello, I am trying to do constrained motion planning using the `TangentBundleStateSpace`. When I try to add my start state with `constraint_space.anchorChart(sstart())`, I am getting `ompl::base::AtlasStateSpace::anchorChart(): Initial chart creation failed. Cannot proceed.` I am also getting:

```
Error:   ompl::base::AtlasStateSpace::newChart(): Failed because manifold looks degenerate here.
         at line 277 in ~/ompl/base/spaces/constraint/src/AtlasStateSpace.cpp
```

My constraint function calculates a target rotation for the end-effector (given the current end-effector position), and calculates the angular distance between this target rotation and the current rotation. For debugging, I made the target rotation is a fixed matrix (i.e. does not depend on the end-effector position) -- in this case, the motion planning seems to work, but not when I try to make it variable...

Any ideas why this might be the case? Thanks!

**Comment by zkingston** [comment]
You can debug this by looking at what the Jacobian of the constraint function is at the starting state. If the Jacobian is not of full rank, you will get this error.

**Comment by jih189** [comment]
In some cases, the Jacobian matrix is not full rank, how should we handle it?
