### ISSUE TITLE
Using CostConvergenceTerminationCondition on python 

### ISSUE THREAD

**Issue by ilyeszak22** [ompl/ompl#901]
Dear Community, 

I am using OMPL with python and I would like to get some help to use the solve(Time) but instead of time with the "CostConvergenceTerminationCondition" where I can set my own "solutionsWindow" and "epsilon"

I don't know how to implement a PlannerTerminationCondition in python. An example would be very helpful.

It should be in this structure but I got confused on what to return with the "__ call __" function: 

```python
class CostConvergencePTC(object):
    def __init__(self, solutionsWindow, epsilon):
        self.solutionsWindow = solutionsWindow
        self.epsilon = epsilon
    def __call__(self):
        return [self.epsilon, self.solutionsWindow]
iptc = CostConvergencePTC(10, 0.1)
solved = self.ss.solve( ob.PlannerTerminationConditionFn(iptc))
```
Thank you very much.

**Comment by zkingston** [comment]
You can simply use the constructor

```py
    solutionsWindow = 10
    epsilon = 0.1
    ccptc = ob.CostConvergenceTerminationCondition(ss.getProblemDefinition(),
                                                   solutionsWindow, epsilon)
```
