### ISSUE TITLE
[Python] How to measure progress over time for algorithms

### ISSUE THREAD

**Issue by Kchour** [ompl/ompl#903]
I want to plot solution costs over time for some algorithms such as BITstar or AITstar using ompl's benchmarking tool + PlannerArena. However, it seems that this is only available for RRT* as discussed [here](https://ompl.kavrakilab.org/benchmark.html). Additionally, I am using the Python bindings and couldn't really figure out how to use `addPlannerProgressProperty`, as discussed in the tutorial. What's the best way to go about doing this?

Thanks!

**Comment by zkingston** [comment]
That documentation is out of date - most (if not all) of the AO planner implement planner progress properties that are captured by benchmarking.
