### ISSUE TITLE
RealVectorStateInternal' object has no attribute 'setX'

### ISSUE THREAD

**Issue by hickey23** [ompl/ompl#910]
![1](https://user-images.githubusercontent.com/50687983/175187239-c5b90a3c-1ab9-4f32-b97a-569232acff1a.png)
hello, I follow the demo(python) of the documentation in the ompl web,but when I run my code, is seems to be wrong!
I am new to ompl,I want to know What went wrong? Thanks for your attention!
Looking for you reply sincerely

**Comment by mamoll** [comment]
RealVectorStateSpace has no method setX. Use array-style indexing instead:
```
start()[0] = .17
start()[1] = .2
```
