### ISSUE TITLE
cannot setRange for KinematicCarPlanning for RRT planner

### ISSUE THREAD

**Issue by MohiniMohiniMohini** [ompl/ompl#917]
I created an object of KinematicCarPlanning and setPlanner as control::RRT. I can setGoalBias and setIntermediateStates but there is not method to setRange for RRT planner. Am I doing anything wrong?

**Comment by ChamzasKonstantinos** [comment]
There is no setRange() function for control::RRT only for geometric:RRT. You can see this in the documentation here: 
https://ompl.kavrakilab.org/classompl_1_1control_1_1RRT.html .

**Comment by MohiniMohiniMohini** [comment]
can you help me understand why is it not available for control? what if I need to change the value to check RRT performance variations?

**Comment by MohiniMohiniMohini** [comment]
@ChamzasKonstantinos any thoughts?
