### ISSUE TITLE
Question about function simplify in PathSimplifier.cpp

### ISSUE THREAD

**Issue by PeterChen607** [ompl/ompl#925]
I have a question about the following part in function `simplify`:

```
        // try a randomized step of connecting vertices
        if (ptc == false || atLeastOnce)
            tryMore = reduceVertices(path);

        // try to collapse close-by vertices
        if (ptc == false || atLeastOnce)
            collapseCloseVertices(path);

        // try to reduce verices some more, if there is any point in doing so
        unsigned int times = 0;
        while ((ptc == false || atLeastOnce) && tryMore && ++times <= 5)
            tryMore = reduceVertices(path);
```

My question is that, why we separate the using of `reduceVertices` function in two parts? Couldn't we just use `collapseCloseVertices` first to simplify the path first, then run `reduceVertices` in a loop?

**Comment by zkingston** [comment]
The path simplifier is simply a collection of heuristics - you can apply the individual heuristics in any order if you want. What you suggest is also possible.
