### ISSUE TITLE
What are the start and goal states for testing wall gap and goal enclosure domains in R4, R8, and R16 for EIT* and AIT*? 

### ISSUE THREAD

**Issue by yw1055** [ompl/ompl#932]
Hi Marlin or whom may concern,
           What are the start and goal states for testing wall gap and goal enclosure domains in R4, R8, and R16 in EIT*  and AIT*? The papers just showed the (x,y) locations. 

Thank you,
Yi

**Comment by marlinstrub** [comment]
All coordinates that are not specified in the figure were set to zero.
