### ISSUE TITLE
What do I cite if I use PathSimplifier?

### ISSUE THREAD

**Issue by werner291** [ompl/ompl#933]
Hello,

more of a citation-related question than anything implementation-related...

I noticed that the use of `PathSimplifier::perturbPath` and `PathSimplifier::shortcutPath` greatly improve the results of my experiments, but I'm not too sure about who or what to cite for the algorithms used in these methods.

Are these published in literature somewhere, or should I just cite OMPL itself for these?

**Comment by zkingston** [comment]
I'd cite the following:
Geraerts, Roland, and Mark H. Overmars. "Creating high-quality paths for motion planning." The international journal of robotics research 26.8 (2007): 845-863.

**Comment by werner291** [comment]
Thanks!

**Comment by werner291** [comment]
Actually, that one presents shortcutting only, not random perturbation... I'll see if I can find one for that too.

**Comment by werner291** [comment]
There's a version of the random displacement algorithm published as part of _Task Constrained Motion Planning in Robot Joint Space_ by Mike Stilman too
