### ISSUE TITLE
Installing python bindings in Ubuntu 20.04

### ISSUE THREAD

**Issue by sadiq26** [ompl/ompl#938]
Hello
While using the installation script, i get the following error
I am using Ubuntu 20.04 and python version 20.04.

salman@Sadiq:~/Motion_Planning_Final/Attempt_1_OMPL/omplapp-1.5.2-Source(1)/omplapp-1.5.2-Source/build/Release$ make -j 4
[  0%] Building CXX object ompl/src/ompl/CMakeFiles/ompl.dir/base/src/Constraint.cpp.o
[  0%] Building CXX object ompl/src/ompl/CMakeFiles/ompl.dir/base/src/DiscreteMotionValidator.cpp.o
...
...
[  0%] Building CXX object ompl/src/ompl/CMakeFiles/ompl.dir/extensions/ode/src/OpenDEStateSpace.cpp.o
[  0%] Building CXX object ompl/src/ompl/CMakeFiles/ompl.dir/extensions/ode/src/OpenDEStateValidityChecker.cpp.o
[  0%] Linking CXX shared library ../../../lib/libompl.so
/bin/sh: 1: Syntax error: "(" unexpected
make[2]: *** [ompl/src/ompl/CMakeFiles/ompl.dir/build.make:2879: lib/libompl.so.1.5.2] Error 2
make[2]: *** Deleting file 'lib/libompl.so.1.5.2'
make[1]: *** [CMakeFiles/Makefile2:698: ompl/src/ompl/CMakeFiles/ompl.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by zkingston** [comment]
See #956 for continued discussion.
