### ISSUE TITLE
PathGeometric::checkAndRepair problem

### ISSUE THREAD

**Issue by krakjack5** [ompl/ompl#942]
I am experimenting with checking and repairing Dubin's paths and came across a peculiar behavior. I defined a geometric path in Dubin's state space, set a state validator in the appropriate space information. When I ran path_geometric.check() it worked as expected and correctly identified invalid paths. However if I ran path_geometric.checkAndRepair, then it always returned (true, true) indicating the original path to be valid and no repair run. Going through the code there seems to be a small difference in PathGeometric::check and PathGeometric::checkAndRepair methods. The check method includes the following two lines which are missing from checkAndRepair. It is a bit unclear to me when calling setup is necessary.

```
// make sure state validity checker is set
If (!si_->isSetup())
    si_->setup();
```

Should PathGeometric::checkAndRepair also include the above two lines? When I manually called setup on the space information object in my code, checkAndRepair worked as expected as illustrated in the following code snippet.

```
	auto state_space = std::make_shared<ob::DubinsStateSpace>(min_turn_radius_m);
	ob::SpaceInformationPtr si = std::make_shared<ob::SpaceInformation>(state_space);

	// set up validity checker
	state_space->setBounds(ComputeBounds());
	si->setStateValidityChecker(std::make_shared<CollisionDetector>(si));

	// generate states along the path and build geometric path
	std::vector<ob::ScopedState<ob::DubinsStateSpace>> states;
	for (auto const& p : path) { // path is a vector with each element having x, y and phi
		ob::ScopedState<ob::DubinsStateSpace> s{state_space};
		s->setXY(p.x, p.y);
		s->setYaw(p.phi);
		state_space->enforceBounds(s.get());
		states.emplace_back(std::move(s));
	}
	og::PathGeometric path_geometric{si};
	for (auto const& s : states) {
		path_geometric.append(s.get());
	}

        // works correctly
        auto valid = path_geometric.check();

        // always returns (true, true)
        // however, if the following line is added then it works correctly
        //si->setup();
        auto check_and_repair_result = path_geometric.checkAndRepair(ompl::magic::MAX_VALID_SAMPLE_ATTEMPTS);
```

Thank you for your help!

**Comment by zkingston** [comment]
Yes, you are not setting your space up before using functions that require setup. Adding this to the start of checkAndRepair would be fine.
