### ISSUE TITLE
OMPL RRT* result

### ISSUE THREAD

**Issue by Tommyliu23** [ompl/ompl#960]
![~TH EQ% I8X{ MA HNF5LLW](https://user-images.githubusercontent.com/102798363/206100588-de7419bd-5035-40b6-a244-f62e8789801f.png)
Hello, this is the first time for me to use OMPL. When I plan a path with the RRT * that comes with OMPL, the terminal returns such data. Can you tell me what these two data mean? Does it represent the he number of vertices required to search for a path in the RRT * planning process? How can I get these two data?
thank you for your reply sincerely !

**Comment by zkingston** [comment]
RRT* is an asymptotically optimal planner - it will find an initial solution (the 18 vertices in graph statement), and will continue to refine that solution (the final # of states - see that the cost went from 21.58 to 20.502). Planner graph data can be extracted with the PlannerData class.
