### ISSUE TITLE
Wrong video link in ABIT* documentation page

### ISSUE THREAD

**Issue by andreas-botbuilt** [ompl/ompl#963]
The [documentation page for ABIT*](https://ompl.kavrakilab.org/classompl_1_1geometric_1_1ABITstar.html#details) contains a link to a video of AIT* at this line: https://github.com/ompl/ompl/blob/main/src/ompl/geometric/planners/informedtrees/ABITstar.h#L82. Instead, the link should be to this video of ABIT*: https://www.youtube.com/watch?v=VFdihv8Lq2A.

**Comment by marlinstrub** [comment]
Nice catch, thanks for reporting!
