### ISSUE TITLE
Moveit workspace wouldn't compile after OMPL update

### ISSUE THREAD

**Issue by vivekcdavid** [ompl/ompl#982]
Today my Ubuntu Today morning Ubuntu automatically updated my ROS OMPL from 1.5 to version 1.6 and now my moveit workspace wouldn't compile and i am getting this error.

/home/sawyer/ws_moveit/src/moveit/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h:46:10: fatal error: ompl/base/State.h : No such file or directory
   46 | #include <ompl/base/State.h >

Do you know why it is happening?
Any help is appreciated.

**Comment by zkingston** [comment]
Can you clean and build your environment? It might be looking for versioned headers.

**Comment by vivekcdavid** [comment]
I tried it multiple times but it was not working, in the end, I had to build a new moveit workspace from scratch and then copy the different packages from the old workspace skipping the packages that were created from the moveit . Now it is compiling.
