### ISSUE TITLE
ompl  python building build issue on arm platform not work

### ISSUE THREAD

**Issue by tuanhe** [ompl/ompl#985]
I need to highlight the summarize firstly
None of the issue answer solved! including #725, #981
yes, the log we met the same shows below:
ERROR error occured, while parsing element with name "Field" and attrs "['id', 'name', 'type', 'context', 'access', 'offset']".
Error: 'line'.
Error: can't generate code for module util

I am sure this issue cannot reproduce on X86 and Mac M1, but can be easily reproduce on Arm platform . such as raspberry and NVIDIA Jetson series

**Comment by zkingston** [comment]
This is the same issue as reported in #981, please keep discussion there.
